<a href="https://colab.research.google.com/github/JaimeTS/hyrox-analysis/blob/main/notebooks/01_scraping_hyrox.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Scraping de resultados HYROX

Objetivo: descargar los resultados de una prueba concreta desde HyResult y convertirlos en una base de datos estructurada para análisis de rendimiento, pacing y diferencias por edad y sexo.

## 1. Carga de librerías

Cargamos las librerías necesarias para descargar páginas web, leer HTML, estructurar datos en tablas y controlar pausas entre peticiones.

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import math
import time

## 2. Parámetros iniciales

Definimos la URL base de HyResult, la URL del evento y la URL de la categoría que vamos a descargar inicialmente.

In [ ]:
BASE_URL = "https://www.hyresult.com"

event_url = "https://www.hyresult.com/event/s8-2026-barcelona"
ranking_url = "https://www.hyresult.com/ranking/s8-2026-barcelona-hyrox-men"

headers = {
    "User-Agent": "Mozilla/5.0"
}

## 3. Extracción de enlaces a rankings del evento

La página del evento contiene enlaces a las distintas divisiones de la prueba. Extraemos esos enlaces para poder automatizar posteriormente la descarga de varias categorías.

In [ ]:
response_event = requests.get(event_url, headers=headers)
soup_event = BeautifulSoup(response_event.text, "html.parser")

links = []

for a in soup_event.find_all("a", href=True):
    href = a["href"]
    texto = a.get_text(strip=True)
    links.append((texto, href))

links_df = pd.DataFrame(links, columns=["texto", "href"])

ranking_links = links_df[
    links_df["href"].str.contains("/ranking/", case=False, na=False)
].drop_duplicates()

ranking_links

      texto                                               href
40  Ranking               /ranking/s8-2026-barcelona-hyrox-men
41  Ranking             /ranking/s8-2026-barcelona-hyrox-women
42  Ranking       /ranking/s8-2026-barcelona-hyrox-doubles-men
43  Ranking     /ranking/s8-2026-barcelona-hyrox-doubles-women
44  Ranking     /ranking/s8-2026-barcelona-hyrox-doubles-mixed
45  Ranking           /ranking/s8-2026-barcelona-hyrox-pro-men
46  Ranking         /ranking/s8-2026-barcelona-hyrox-pro-women
47  Ranking   /ranking/s8-2026-barcelona-hyrox-pro-doubles-men
48  Ranking  /ranking/s8-2026-barcelona-hyrox-pro-doubles-w...
49  Ranking    /ranking/s8-2026-barcelona-hyrox-team-relay-men
50  Ranking  /ranking/s8-2026-barcelona-hyrox-team-relay-women
51  Ranking  /ranking/s8-2026-barcelona-hyrox-team-relay-mixed
52  Ranking      /ranking/s8-2026-barcelona-hyrox-adaptive-men
53  Ranking    /ranking/s8-2026-barcelona-hyrox-adaptive-women

## 4. Función robusta para extraer una página del ranking

HyResult presenta normalmente un atleta por fila, aunque algunas posiciones aparecen divididas en varias filas consecutivas. Esta función reconstruye automáticamente esos casos para obtener todos los participantes de la página.

In [ ]:
def extraer_ranking_pagina(url):
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")

    rows = soup.find_all("tr")
    resultados = []

    i = 0

    while i < len(rows):
        cells = rows[i].find_all("td")
        textos = [c.get_text(" ", strip=True) for c in cells]

        # ==========================================================
        # CASO NORMAL
        # ==========================================================
        if len(cells) >= 7:

            posicion = cells[1].get_text(strip=True)
            posicion_ag = cells[2].get_text(strip=True)

            name_cell = cells[3]
            link_athlete = name_cell.find("a")
            img_flag = name_cell.find("img")

            nombre = link_athlete.get_text(strip=True) if link_athlete else None
            athlete_url = (
                link_athlete["href"]
                if link_athlete and link_athlete.has_attr("href")
                else None
            )

            pais = (
                img_flag["title"]
                if img_flag and img_flag.has_attr("title")
                else None
            )

            grupo_edad = cells[4].get_text(strip=True)
            tiempo = cells[5].get_text(strip=True)

            analyze_link = cells[6].find("a")
            analyze_url = (
                analyze_link["href"]
                if analyze_link and analyze_link.has_attr("href")
                else None
            )

            if nombre and tiempo and analyze_url:

                resultados.append({
                    "posicion": posicion,
                    "posicion_grupo_edad": posicion_ag,
                    "nombre": nombre,
                    "pais": pais,
                    "grupo_edad": grupo_edad,
                    "tiempo": tiempo,
                    "athlete_url": athlete_url,
                    "analyze_url": analyze_url
                })

            i += 1
            continue

        # ==========================================================
        # CASO ESPECIAL A
        # ==========================================================
        if len(cells) >= 3 and i + 4 < len(rows):

            posicion = cells[1].get_text(strip=True)
            posicion_ag = cells[2].get_text(strip=True)

            row_nombre = rows[i + 1]
            row_grupo = rows[i + 2]
            row_tiempo = rows[i + 3]
            row_analyze = rows[i + 4]

            nombre_cell = row_nombre.find("td")
            link_athlete = nombre_cell.find("a") if nombre_cell else None
            img_flag = nombre_cell.find("img") if nombre_cell else None

            nombre = link_athlete.get_text(strip=True) if link_athlete else None
            athlete_url = (
                link_athlete["href"]
                if link_athlete and link_athlete.has_attr("href")
                else None
            )

            pais = (
                img_flag["title"]
                if img_flag and img_flag.has_attr("title")
                else None
            )

            grupo_edad = row_grupo.get_text(" ", strip=True)
            tiempo = row_tiempo.get_text(" ", strip=True)

            analyze_link = row_analyze.find("a")
            analyze_url = (
                analyze_link["href"]
                if analyze_link and analyze_link.has_attr("href")
                else None
            )

            if nombre and tiempo and analyze_url:

                resultados.append({
                    "posicion": posicion,
                    "posicion_grupo_edad": posicion_ag,
                    "nombre": nombre,
                    "pais": pais,
                    "grupo_edad": grupo_edad,
                    "tiempo": tiempo,
                    "athlete_url": athlete_url,
                    "analyze_url": analyze_url
                })

                i += 5
                continue

        # ==========================================================
        # CASO ESPECIAL C
        # (fila vacía + datos repartidos)
        # ==========================================================
        if len(cells) == 1 and textos == [""] and i + 6 < len(rows):

            row_pos = rows[i + 1]
            row_pos_ag = rows[i + 2]
            row_nombre = rows[i + 3]
            row_grupo = rows[i + 4]
            row_tiempo = rows[i + 5]
            row_analyze = rows[i + 6]

            posicion = row_pos.get_text(" ", strip=True)
            posicion_ag = row_pos_ag.get_text(" ", strip=True)
            nombre = row_nombre.get_text(" ", strip=True)
            grupo_edad = row_grupo.get_text(" ", strip=True)
            tiempo = row_tiempo.get_text(" ", strip=True)

            analyze_link = row_analyze.find("a")
            analyze_url = (
                analyze_link["href"]
                if analyze_link and analyze_link.has_attr("href")
                else None
            )

            if (
                posicion.isdigit()
                and posicion_ag.isdigit()
                and nombre
                and tiempo
                and analyze_url
            ):

                resultados.append({
                    "posicion": posicion,
                    "posicion_grupo_edad": posicion_ag,
                    "nombre": nombre,
                    "pais": None,
                    "grupo_edad": grupo_edad,
                    "tiempo": tiempo,
                    "athlete_url": None,
                    "analyze_url": analyze_url
                })

                i += 7
                continue

        # ==========================================================
        # CASO ESPECIAL B
        # ==========================================================
        if len(cells) >= 2 and i + 5 < len(rows):

            posicion = cells[1].get_text(strip=True)

            row_pos_ag = rows[i + 1]
            row_nombre = rows[i + 2]
            row_grupo = rows[i + 3]
            row_tiempo = rows[i + 4]
            row_analyze = rows[i + 5]

            posicion_ag = row_pos_ag.get_text(" ", strip=True)

            nombre_cell = row_nombre.find("td")
            link_athlete = nombre_cell.find("a") if nombre_cell else None
            img_flag = nombre_cell.find("img") if nombre_cell else None

            nombre = link_athlete.get_text(strip=True) if link_athlete else None
            athlete_url = (
                link_athlete["href"]
                if link_athlete and link_athlete.has_attr("href")
                else None
            )

            pais = (
                img_flag["title"]
                if img_flag and img_flag.has_attr("title")
                else None
            )

            grupo_edad = row_grupo.get_text(" ", strip=True)
            tiempo = row_tiempo.get_text(" ", strip=True)

            analyze_link = row_analyze.find("a")
            analyze_url = (
                analyze_link["href"]
                if analyze_link and analyze_link.has_attr("href")
                else None
            )

            if nombre and tiempo and analyze_url:

                resultados.append({
                    "posicion": posicion,
                    "posicion_grupo_edad": posicion_ag,
                    "nombre": nombre,
                    "pais": pais,
                    "grupo_edad": grupo_edad,
                    "tiempo": tiempo,
                    "athlete_url": athlete_url,
                    "analyze_url": analyze_url
                })

                i += 6
                continue

        i += 1

    df = pd.DataFrame(resultados)

    if len(df) > 0:

        df["athlete_url"] = df["athlete_url"].apply(
            lambda x: BASE_URL + x if isinstance(x, str) and x.startswith("/") else x
        )

        df["analyze_url"] = df["analyze_url"].apply(
            lambda x: BASE_URL + x if isinstance(x, str) and x.startswith("/") else x
        )

    return df

## 5. Prueba de extracción de una página

Probamos la función con la primera página y comprobamos que recupera las 100 posiciones.

In [ ]:
df_pagina_1 = extraer_ranking_pagina(ranking_url)

print("Filas extraídas:", len(df_pagina_1))

df_pagina_1.head(10)

Filas extraídas: 100

,posicion,posicion_grupo_edad,nombre,pais,grupo_edad,tiempo,athlete_url,analyze_url
0,1,1,Gaetan Gianni,France,16-24,53:44,https://www.hyresult.com/athlete/gaetan-gianni,https://www.hyresult.com/result/LR3MS4JI502C48
1,2,1,Emilio Aguayo,Spain,35-39,56:38,https://www.hyresult.com/athlete/emilio-aguayo,https://www.hyresult.com/result/LR3MS4JI501875
2,3,1,Loic Cebelieu,France,25-29,57:17,https://www.hyresult.com/athlete/loic-cebelieu,https://www.hyresult.com/result/LR3MS4JI5010E6
3,4,1,Ferran Bochaca Sabarich,Spain,30-34,57:24,https://www.hyresult.com/athlete/ferran-bochac...,https://www.hyresult.com/result/LR3MS4JI501D84
4,5,2,Alberto Casado Aroca,Spain,30-34,57:38,https://www.hyresult.com/athlete/alberto-casad...,https://www.hyresult.com/result/LR3MS4JI502972
5,6,3,Sebastien Rajkowski,France,30-34,58:10,https://www.hyresult.com/athlete/sebastien-raj...,https://www.hyresult.com/result/LR3MS4JI5022B0
6,7,4,Mehdi Berrouigat,France,30-34,58:19,https://www.hyresult.com/athlete/mehdi-berrouigat,https://www.hyresult.com/result/LR3MS4JI503639
7,8,2,Pau Nacenta Merinas,Spain,25-29,58:35,https://www.hyresult.com/athlete/pau-nacenta-m...,https://www.hyresult.com/result/LR3MS4JI50188C
8,9,3,Aaron Timmerman,Belgium,25-29,58:38,https://www.hyresult.com/athlete/aaron-timmerman,https://www.hyresult.com/result/LR3MS4JI500DE4
9,10,4,Walter Paladina,Italy,25-29,58:41,https://www.hyresult.com/athlete/walter-paladina,https://www.hyresult.com/result/LR3MS4JI502477

## 6. Función para descargar una categoría completa

HyResult pagina los rankings en bloques de 100 participantes. Esta función recorre todas las páginas de una categoría y concatena los resultados en un único DataFrame.

In [ ]:
def descargar_categoria_completa(ranking_url, total_atletas, pausa=0.5):
    participantes_por_pagina = 100
    num_paginas = math.ceil(total_atletas / participantes_por_pagina)

    dfs = []

    for pagina in range(1, num_paginas + 1):
        url = f"{ranking_url}?p={pagina}"

        print(f"Descargando página {pagina}/{num_paginas}")

        df_pagina = extraer_ranking_pagina(url)
        dfs.append(df_pagina)

        time.sleep(pausa)

    df_categoria = pd.concat(dfs, ignore_index=True)

    return df_categoria

## 7. Descarga de HYROX Men Barcelona 2026

Aplicamos la función a la categoría HYROX Men del evento Barcelona 2026. En la página del evento esta categoría aparece con 2350 atletas.

In [ ]:
total_atletas = 2350

df_categoria = descargar_categoria_completa(
    ranking_url=ranking_url,
    total_atletas=total_atletas,
    pausa=0.5
)

print("Participantes extraídos:", len(df_categoria))

df_categoria.tail()

Descargando página 1/24
Descargando página 2/24
Descargando página 3/24
Descargando página 4/24
Descargando página 5/24
Descargando página 6/24
Descargando página 7/24
Descargando página 8/24
Descargando página 9/24
Descargando página 10/24
Descargando página 11/24
Descargando página 12/24
Descargando página 13/24
Descargando página 14/24
Descargando página 15/24
Descargando página 16/24
Descargando página 17/24
Descargando página 18/24
Descargando página 19/24
Descargando página 20/24
Descargando página 21/24
Descargando página 22/24
Descargando página 23/24
Descargando página 24/24
Participantes extraídos: 2349

,posicion,posicion_grupo_edad,nombre,pais,grupo_edad,tiempo,athlete_url,analyze_url
2344,2346,23,Carlos Barreto,Puerto Rico,60-64,2:36:53,https://www.hyresult.com/athlete/carlos-barreto,https://www.hyresult.com/result/LR3MS4JI5036F1
2345,2347,24,Emmanuel Weill,France,60-64,2:38:29,https://www.hyresult.com/athlete/emmanuel-weill,https://www.hyresult.com/result/LR3MS4JI503BBC
2346,2348,286,Mo Mo,United States,40-44,2:51:02,https://www.hyresult.com/athlete/mo-mo,https://www.hyresult.com/result/LR3MS4JI503D47
2347,2349,159,Nicolas Taillard,France,45-49,2:53:32,https://www.hyresult.com/athlete/nicolas-taillard,https://www.hyresult.com/result/LR3MS4JI501C3E
2348,2350,461,Avisek Mohanty,India,35-39,3:08:24,https://www.hyresult.com/athlete/avisek-mohanty,https://www.hyresult.com/result/LR3MS4JI50381A

## 8. Control de calidad de la extracción

Comprobamos si el número de participantes extraídos coincide con el total esperado y si hay posiciones duplicadas o faltantes.

In [ ]:
df_categoria["posicion"] = pd.to_numeric(df_categoria["posicion"], errors="coerce")
df_categoria["posicion_grupo_edad"] = pd.to_numeric(df_categoria["posicion_grupo_edad"], errors="coerce")

print("Total esperado:", total_atletas)
print("Total extraído:", len(df_categoria))

print("Posición mínima:", df_categoria["posicion"].min())
print("Posición máxima:", df_categoria["posicion"].max())

print("Posiciones duplicadas:", df_categoria["posicion"].duplicated().sum())

posiciones_esperadas = set(range(1, total_atletas + 1))
posiciones_observadas = set(df_categoria["posicion"].dropna().astype(int))

posiciones_faltantes = sorted(posiciones_esperadas - posiciones_observadas)

print("Número de posiciones faltantes:", len(posiciones_faltantes))
print("Primeras posiciones faltantes:", posiciones_faltantes[:20])

Total esperado: 2350
Total extraído: 2349
Posición mínima: 1
Posición máxima: 2350
Posiciones duplicadas: 0
Número de posiciones faltantes: 1
Primeras posiciones faltantes: [403]

EN HYROX BARCELONA 2026, EXISTE UN PROBLEMA CON LA POSICIÓN 403 DONDE NO APARECE CON LA DESCARGA NI EL NOMBRE NI EL ENLACE DEL ATLETA

## 9. Exportación de resultados

Guardamos la base de datos de la categoría en formato CSV para reutilizarla en análisis posteriores.

In [ ]:
nombre_archivo = "barcelona2026_hyrox_men.csv"

df_categoria.to_csv(
    nombre_archivo,
    index=False
)

print("Archivo guardado:", nombre_archivo)

Archivo guardado: barcelona2026_hyrox_men.csv

## 10. Descarga de la pestaña splits (datos individuales)

La página individual del atleta tiene varias pestañas. Los parciales parecen estar en la pestaña `Splits`, accesible mediante el parámetro `?tab=splits`.

In [90]:
## URL de splits de un atleta

url_resultado = df_categoria.loc[0, "analyze_url"]
url_splits = url_resultado + "?tab=splits"

response_splits = requests.get(url_splits, headers=headers)
soup_splits = BeautifulSoup(response_splits.text, "html.parser")

texto_splits = soup_splits.get_text(" | ", strip=True)

print("URL:", url_splits)
print("Código:", response_splits.status_code)
print("Longitud HTML:", len(response_splits.text))
print(texto_splits[:4000])

URL: https://www.hyresult.com/result/LR3MS4JI502C48?tab=splits
Código: 200
Longitud HTML: 193179
Home | Events | Compare | Rankings | All Time Ranking | Legends Ranking | Elite Points Ranking | Simulator | Locations | Toggle navigation | Search | Loading data ... | WE 💛 HYROX! | HYRESULT is your source for all HYROX data. Find HYROX rankings, athlete profiles, race analytics, start lists by wave, detailed comparisons and race time simulators. | App | Home | Compare | Events | Simulator | Locations | Rankings | Station guides | HYROX Guide | Run | SkiErg | Sled Push | Sled Pull | Burpee Broad Jump | Row | Farmers Carry | Sandbag Lunges | Wall Balls | Company & legal | About | Partner | Privacy | Legal | Connect | Contact | @hyresult | © | 2026 | HYRESULT GmbH. All rights reserved. | Home | Events | Compare | Rankings | All Time Ranking | Legends Ranking | Elite Points Ranking | Simulator | Locations | HYROX race analysis for Gaetan Gianni at HYROX Barcelona 2026 • HYRESULT | Events | / | Barcelona 2026 | / | MEN | Gaetan Gianni | 53:44 | # | 1 | of | 2350 | # | 1 | in AG | 16-24 | Loading data ... | Totals | Runs | Workouts | Splits | Simulator | Split | Time of Day | Time | Diff | Roxzone In | 08:53:23 | 03:21 | 03:21 | SkiErg In | 08:53:26 | 03:23 | 0:02 | SkiErg Out | 08:57:25 | 07:23 | 04:00 | Roxzone Out | 08:57:28 | 07:25 | 0:02 | Roxzone In | 09:00:50 | 10:47 | 03:22 | Sled Push In | 09:01:02 | 11:00 | 0:13 | Sled Push Out | 09:03:10 | 13:07 | 02:07 | Roxzone Out | 09:03:13 | 13:11 | 0:04 | Roxzone In | 09:06:43 | 16:41 | 03:30 | Sled Pull In | 09:06:58 | 16:56 | 0:15 | Sled Pull Out | 09:09:51 | 19:48 | 02:52 | Roxzone Out | 09:10:02 | 19:59 | 0:11 | Roxzone In | 09:13:26 | 23:24 | 03:25 | Burpee Broad Jump In | 09:13:30 | 23:27 | 0:03 | Burpee Broad Jump Out | 09:15:45 | 25:42 | 02:15 | Roxzone Out | 09:16:09 | 26:07 | 0:25 | Roxzone In | 09:19:34 | 29:31 | 03:24 | Row In | 09:19:38 | 29:35 | 0:04 | Row Out | 09:23:44 | 33:42 | 04:07 | Roxzone Out | 09:24:14 | 34:12 | 0:30 | Roxzone In | 09:27:39 | 37:36 | 03:24 | Farmers Carry In | 09:27:51 | 37:48 | 0:12 | Farmers Carry Out | 09:29:21 | 39:18 | 01:30 | Roxzone Out | 09:29:55 | 39:52 | 0:34 | Roxzone In | 09:33:16 | 43:13 | 03:21 | Sandbag Lunges In | 09:33:26 | 43:24 | 0:11 | Sandbag Lunges Out | 09:36:05 | 46:02 | 02:38 | Roxzone Out | 09:36:40 | 46:38 | 0:36 | Wall Balls In | 09:40:07 | 50:05 | 03:27 | Total time | 09:43:46 | 53:44 | 03:39

In [91]:
palabras_clave_splits = [
    "Run 1",
    "SkiErg",
    "Run 2",
    "Sled Push",
    "Run 3",
    "Sled Pull",
    "Run 4",
    "Burpee Broad Jump",
    "Run 5",
    "Row",
    "Run 6",
    "Farmers Carry",
    "Run 7",
    "Sandbag Lunges",
    "Run 8",
    "Wall Balls",
    "Roxzone"
]

for palabra in palabras_clave_splits:
    indice = texto_splits.find(palabra)
    print("\n" + "="*80)
    print("Palabra:", palabra)
    print("Índice:", indice)

    if indice != -1:
        print(texto_splits[indice:indice+1000])

================================================================================
Palabra: Run 1
Índice: -1

================================================================================
Palabra: SkiErg
Índice: 456
SkiErg | Sled Push | Sled Pull | Burpee Broad Jump | Row | Farmers Carry | Sandbag Lunges | Wall Balls | Company & legal | About | Partner | Privacy | Legal | Connect | Contact | @hyresult | © | 2026 | HYRESULT GmbH. All rights reserved. | Home | Events | Compare | Rankings | All Time Ranking | Legends Ranking | Elite Points Ranking | Simulator | Locations | HYROX race analysis for Gaetan Gianni at HYROX Barcelona 2026 • HYRESULT | Events | / | Barcelona 2026 | / | MEN | Gaetan Gianni | 53:44 | # | 1 | of | 2350 | # | 1 | in AG | 16-24 | Loading data ... | Totals | Runs | Workouts | Splits | Simulator | Split | Time of Day | Time | Diff | Roxzone In | 08:53:23 | 03:21 | 03:21 | SkiErg In | 08:53:26 | 03:23 | 0:02 | SkiErg Out | 08:57:25 | 07:23 | 04:00 | Roxzone Out | 08:57:28 | 07:25 | 0:02 | Roxzone In | 09:00:50 | 10:47 | 03:22 | Sled Push In | 09:01:02 | 11:00 | 0:13 | Sled Push Out | 09:03:10 | 13:07 | 02:07 | Roxzone Out | 09:03:13 | 13:11 | 0:04 | Roxzone In | 09:06:43 | 16:41 |

================================================================================
Palabra: Run 2
Índice: -1

================================================================================
Palabra: Sled Push
Índice: 465
Sled Push | Sled Pull | Burpee Broad Jump | Row | Farmers Carry | Sandbag Lunges | Wall Balls | Company & legal | About | Partner | Privacy | Legal | Connect | Contact | @hyresult | © | 2026 | HYRESULT GmbH. All rights reserved. | Home | Events | Compare | Rankings | All Time Ranking | Legends Ranking | Elite Points Ranking | Simulator | Locations | HYROX race analysis for Gaetan Gianni at HYROX Barcelona 2026 • HYRESULT | Events | / | Barcelona 2026 | / | MEN | Gaetan Gianni | 53:44 | # | 1 | of | 2350 | # | 1 | in AG | 16-24 | Loading data ... | Totals | Runs | Workouts | Splits | Simulator | Split | Time of Day | Time | Diff | Roxzone In | 08:53:23 | 03:21 | 03:21 | SkiErg In | 08:53:26 | 03:23 | 0:02 | SkiErg Out | 08:57:25 | 07:23 | 04:00 | Roxzone Out | 08:57:28 | 07:25 | 0:02 | Roxzone In | 09:00:50 | 10:47 | 03:22 | Sled Push In | 09:01:02 | 11:00 | 0:13 | Sled Push Out | 09:03:10 | 13:07 | 02:07 | Roxzone Out | 09:03:13 | 13:11 | 0:04 | Roxzone In | 09:06:43 | 16:41 | 03:30 |

================================================================================
Palabra: Run 3
Índice: -1

================================================================================
Palabra: Sled Pull
Índice: 477
Sled Pull | Burpee Broad Jump | Row | Farmers Carry | Sandbag Lunges | Wall Balls | Company & legal | About | Partner | Privacy | Legal | Connect | Contact | @hyresult | © | 2026 | HYRESULT GmbH. All rights reserved. | Home | Events | Compare | Rankings | All Time Ranking | Legends Ranking | Elite Points Ranking | Simulator | Locations | HYROX race analysis for Gaetan Gianni at HYROX Barcelona 2026 • HYRESULT | Events | / | Barcelona 2026 | / | MEN | Gaetan Gianni | 53:44 | # | 1 | of | 2350 | # | 1 | in AG | 16-24 | Loading data ... | Totals | Runs | Workouts | Splits | Simulator | Split | Time of Day | Time | Diff | Roxzone In | 08:53:23 | 03:21 | 03:21 | SkiErg In | 08:53:26 | 03:23 | 0:02 | SkiErg Out | 08:57:25 | 07:23 | 04:00 | Roxzone Out | 08:57:28 | 07:25 | 0:02 | Roxzone In | 09:00:50 | 10:47 | 03:22 | Sled Push In | 09:01:02 | 11:00 | 0:13 | Sled Push Out | 09:03:10 | 13:07 | 02:07 | Roxzone Out | 09:03:13 | 13:11 | 0:04 | Roxzone In | 09:06:43 | 16:41 | 03:30 | Sled Pull In

================================================================================
Palabra: Run 4
Índice: -1

================================================================================
Palabra: Burpee Broad Jump
Índice: 489
Burpee Broad Jump | Row | Farmers Carry | Sandbag Lunges | Wall Balls | Company & legal | About | Partner | Privacy | Legal | Connect | Contact | @hyresult | © | 2026 | HYRESULT GmbH. All rights reserved. | Home | Events | Compare | Rankings | All Time Ranking | Legends Ranking | Elite Points Ranking | Simulator | Locations | HYROX race analysis for Gaetan Gianni at HYROX Barcelona 2026 • HYRESULT | Events | / | Barcelona 2026 | / | MEN | Gaetan Gianni | 53:44 | # | 1 | of | 2350 | # | 1 | in AG | 16-24 | Loading data ... | Totals | Runs | Workouts | Splits | Simulator | Split | Time of Day | Time | Diff | Roxzone In | 08:53:23 | 03:21 | 03:21 | SkiErg In | 08:53:26 | 03:23 | 0:02 | SkiErg Out | 08:57:25 | 07:23 | 04:00 | Roxzone Out | 08:57:28 | 07:25 | 0:02 | Roxzone In | 09:00:50 | 10:47 | 03:22 | Sled Push In | 09:01:02 | 11:00 | 0:13 | Sled Push Out | 09:03:10 | 13:07 | 02:07 | Roxzone Out | 09:03:13 | 13:11 | 0:04 | Roxzone In | 09:06:43 | 16:41 | 03:30 | Sled Pull In | 09:06:58

================================================================================
Palabra: Run 5
Índice: -1

================================================================================
Palabra: Row
Índice: 509
Row | Farmers Carry | Sandbag Lunges | Wall Balls | Company & legal | About | Partner | Privacy | Legal | Connect | Contact | @hyresult | © | 2026 | HYRESULT GmbH. All rights reserved. | Home | Events | Compare | Rankings | All Time Ranking | Legends Ranking | Elite Points Ranking | Simulator | Locations | HYROX race analysis for Gaetan Gianni at HYROX Barcelona 2026 • HYRESULT | Events | / | Barcelona 2026 | / | MEN | Gaetan Gianni | 53:44 | # | 1 | of | 2350 | # | 1 | in AG | 16-24 | Loading data ... | Totals | Runs | Workouts | Splits | Simulator | Split | Time of Day | Time | Diff | Roxzone In | 08:53:23 | 03:21 | 03:21 | SkiErg In | 08:53:26 | 03:23 | 0:02 | SkiErg Out | 08:57:25 | 07:23 | 04:00 | Roxzone Out | 08:57:28 | 07:25 | 0:02 | Roxzone In | 09:00:50 | 10:47 | 03:22 | Sled Push In | 09:01:02 | 11:00 | 0:13 | Sled Push Out | 09:03:10 | 13:07 | 02:07 | Roxzone Out | 09:03:13 | 13:11 | 0:04 | Roxzone In | 09:06:43 | 16:41 | 03:30 | Sled Pull In | 09:06:58 | 16:56 | 0:15 | Sle

================================================================================
Palabra: Run 6
Índice: -1

================================================================================
Palabra: Farmers Carry
Índice: 515
Farmers Carry | Sandbag Lunges | Wall Balls | Company & legal | About | Partner | Privacy | Legal | Connect | Contact | @hyresult | © | 2026 | HYRESULT GmbH. All rights reserved. | Home | Events | Compare | Rankings | All Time Ranking | Legends Ranking | Elite Points Ranking | Simulator | Locations | HYROX race analysis for Gaetan Gianni at HYROX Barcelona 2026 • HYRESULT | Events | / | Barcelona 2026 | / | MEN | Gaetan Gianni | 53:44 | # | 1 | of | 2350 | # | 1 | in AG | 16-24 | Loading data ... | Totals | Runs | Workouts | Splits | Simulator | Split | Time of Day | Time | Diff | Roxzone In | 08:53:23 | 03:21 | 03:21 | SkiErg In | 08:53:26 | 03:23 | 0:02 | SkiErg Out | 08:57:25 | 07:23 | 04:00 | Roxzone Out | 08:57:28 | 07:25 | 0:02 | Roxzone In | 09:00:50 | 10:47 | 03:22 | Sled Push In | 09:01:02 | 11:00 | 0:13 | Sled Push Out | 09:03:10 | 13:07 | 02:07 | Roxzone Out | 09:03:13 | 13:11 | 0:04 | Roxzone In | 09:06:43 | 16:41 | 03:30 | Sled Pull In | 09:06:58 | 16:56 | 0:15 | Sled Pull

================================================================================
Palabra: Run 7
Índice: -1

================================================================================
Palabra: Sandbag Lunges
Índice: 531
Sandbag Lunges | Wall Balls | Company & legal | About | Partner | Privacy | Legal | Connect | Contact | @hyresult | © | 2026 | HYRESULT GmbH. All rights reserved. | Home | Events | Compare | Rankings | All Time Ranking | Legends Ranking | Elite Points Ranking | Simulator | Locations | HYROX race analysis for Gaetan Gianni at HYROX Barcelona 2026 • HYRESULT | Events | / | Barcelona 2026 | / | MEN | Gaetan Gianni | 53:44 | # | 1 | of | 2350 | # | 1 | in AG | 16-24 | Loading data ... | Totals | Runs | Workouts | Splits | Simulator | Split | Time of Day | Time | Diff | Roxzone In | 08:53:23 | 03:21 | 03:21 | SkiErg In | 08:53:26 | 03:23 | 0:02 | SkiErg Out | 08:57:25 | 07:23 | 04:00 | Roxzone Out | 08:57:28 | 07:25 | 0:02 | Roxzone In | 09:00:50 | 10:47 | 03:22 | Sled Push In | 09:01:02 | 11:00 | 0:13 | Sled Push Out | 09:03:10 | 13:07 | 02:07 | Roxzone Out | 09:03:13 | 13:11 | 0:04 | Roxzone In | 09:06:43 | 16:41 | 03:30 | Sled Pull In | 09:06:58 | 16:56 | 0:15 | Sled Pull Out | 09:09:51

================================================================================
Palabra: Run 8
Índice: -1

================================================================================
Palabra: Wall Balls
Índice: 548
Wall Balls | Company & legal | About | Partner | Privacy | Legal | Connect | Contact | @hyresult | © | 2026 | HYRESULT GmbH. All rights reserved. | Home | Events | Compare | Rankings | All Time Ranking | Legends Ranking | Elite Points Ranking | Simulator | Locations | HYROX race analysis for Gaetan Gianni at HYROX Barcelona 2026 • HYRESULT | Events | / | Barcelona 2026 | / | MEN | Gaetan Gianni | 53:44 | # | 1 | of | 2350 | # | 1 | in AG | 16-24 | Loading data ... | Totals | Runs | Workouts | Splits | Simulator | Split | Time of Day | Time | Diff | Roxzone In | 08:53:23 | 03:21 | 03:21 | SkiErg In | 08:53:26 | 03:23 | 0:02 | SkiErg Out | 08:57:25 | 07:23 | 04:00 | Roxzone Out | 08:57:28 | 07:25 | 0:02 | Roxzone In | 09:00:50 | 10:47 | 03:22 | Sled Push In | 09:01:02 | 11:00 | 0:13 | Sled Push Out | 09:03:10 | 13:07 | 02:07 | Roxzone Out | 09:03:13 | 13:11 | 0:04 | Roxzone In | 09:06:43 | 16:41 | 03:30 | Sled Pull In | 09:06:58 | 16:56 | 0:15 | Sled Pull Out | 09:09:51 | 19:48 | 02:52 |

================================================================================
Palabra: Roxzone
Índice: 1103
Roxzone In | 08:53:23 | 03:21 | 03:21 | SkiErg In | 08:53:26 | 03:23 | 0:02 | SkiErg Out | 08:57:25 | 07:23 | 04:00 | Roxzone Out | 08:57:28 | 07:25 | 0:02 | Roxzone In | 09:00:50 | 10:47 | 03:22 | Sled Push In | 09:01:02 | 11:00 | 0:13 | Sled Push Out | 09:03:10 | 13:07 | 02:07 | Roxzone Out | 09:03:13 | 13:11 | 0:04 | Roxzone In | 09:06:43 | 16:41 | 03:30 | Sled Pull In | 09:06:58 | 16:56 | 0:15 | Sled Pull Out | 09:09:51 | 19:48 | 02:52 | Roxzone Out | 09:10:02 | 19:59 | 0:11 | Roxzone In | 09:13:26 | 23:24 | 03:25 | Burpee Broad Jump In | 09:13:30 | 23:27 | 0:03 | Burpee Broad Jump Out | 09:15:45 | 25:42 | 02:15 | Roxzone Out | 09:16:09 | 26:07 | 0:25 | Roxzone In | 09:19:34 | 29:31 | 03:24 | Row In | 09:19:38 | 29:35 | 0:04 | Row Out | 09:23:44 | 33:42 | 04:07 | Roxzone Out | 09:24:14 | 34:12 | 0:30 | Roxzone In | 09:27:39 | 37:36 | 03:24 | Farmers Carry In | 09:27:51 | 37:48 | 0:12 | Farmers Carry Out | 09:29:21 | 39:18 | 01:30 | Roxzone Out | 09:29:55 | 39:52 | 0:34 | Roxzone In

## 11. Extracción de Splits de un atleta

Cada página de resultado contiene una pestaña Splits con el detalle completo de los tiempos acumulados y parciales de carrera y estaciones.

En este bloque extraemos la tabla de splits de un atleta individual.

In [92]:
url_resultado = df_categoria.loc[0, "analyze_url"]

url_splits = url_resultado + "?tab=splits"

response_splits = requests.get(url_splits, headers=headers)

print("Código:", response_splits.status_code)
print("Longitud HTML:", len(response_splits.text))

Código: 200
Longitud HTML: 193179

In [94]:
from io import StringIO

# Convertimos el HTML en tablas de pandas
tablas = pd.read_html(StringIO(response_splits.text))

print("Número de tablas encontradas:", len(tablas))

for i, tabla in enumerate(tablas):

    print("\n" + "="*80)
    print(f"TABLA {i}")
    print("Dimensiones:", tabla.shape)

    display(tabla.head(20))

Número de tablas encontradas: 20

================================================================================
TABLA 0
Dimensiones: (11, 4)

            Split Time of Day   Time   Diff
0      Roxzone In    08:53:23  03:21  03:21
1       SkiErg In    08:53:26  03:23   0:02
2      SkiErg Out    08:57:25  07:23  04:00
3     Roxzone Out    08:57:28  07:25   0:02
4      Roxzone In    09:00:50  10:47  03:22
5    Sled Push In    09:01:02  11:00   0:13
6   Sled Push Out    09:03:10  13:07  02:07
7     Roxzone Out    09:03:13  13:11   0:04
8      Roxzone In    09:06:43  16:41  03:30
9    Sled Pull In    09:06:58  16:56   0:15
10  Sled Pull Out    09:09:51  19:48  02:52

================================================================================
TABLA 1
Dimensiones: (1, 4)

             0         1      2     3
0  Roxzone Out  09:10:02  19:59  0:11

================================================================================
TABLA 2
Dimensiones: (1, 4)

            0         1      2      3
0  Roxzone In  09:13:26  23:24  03:25

================================================================================
TABLA 3
Dimensiones: (1, 4)

                      0         1      2     3
0  Burpee Broad Jump In  09:13:30  23:27  0:03

================================================================================
TABLA 4
Dimensiones: (1, 4)

                       0         1      2      3
0  Burpee Broad Jump Out  09:15:45  25:42  02:15

================================================================================
TABLA 5
Dimensiones: (1, 4)

             0         1      2     3
0  Roxzone Out  09:16:09  26:07  0:25

================================================================================
TABLA 6
Dimensiones: (1, 4)

            0         1      2      3
0  Roxzone In  09:19:34  29:31  03:24

================================================================================
TABLA 7
Dimensiones: (1, 4)

        0         1      2     3
0  Row In  09:19:38  29:35  0:04

================================================================================
TABLA 8
Dimensiones: (1, 4)

         0         1      2      3
0  Row Out  09:23:44  33:42  04:07

================================================================================
TABLA 9
Dimensiones: (1, 4)

             0         1      2     3
0  Roxzone Out  09:24:14  34:12  0:30

================================================================================
TABLA 10
Dimensiones: (1, 4)

            0         1      2      3
0  Roxzone In  09:27:39  37:36  03:24

================================================================================
TABLA 11
Dimensiones: (1, 4)

                  0         1      2     3
0  Farmers Carry In  09:27:51  37:48  0:12

================================================================================
TABLA 12
Dimensiones: (1, 4)

                   0         1      2      3
0  Farmers Carry Out  09:29:21  39:18  01:30

================================================================================
TABLA 13
Dimensiones: (1, 4)

             0         1      2     3
0  Roxzone Out  09:29:55  39:52  0:34

================================================================================
TABLA 14
Dimensiones: (1, 4)

            0         1      2      3
0  Roxzone In  09:33:16  43:13  03:21

================================================================================
TABLA 15
Dimensiones: (1, 4)

                   0         1      2     3
0  Sandbag Lunges In  09:33:26  43:24  0:11

================================================================================
TABLA 16
Dimensiones: (1, 4)

                    0         1      2      3
0  Sandbag Lunges Out  09:36:05  46:02  02:38

================================================================================
TABLA 17
Dimensiones: (1, 4)

             0         1      2     3
0  Roxzone Out  09:36:40  46:38  0:36

================================================================================
TABLA 18
Dimensiones: (1, 4)

               0         1      2      3
0  Wall Balls In  09:40:07  50:05  03:27

================================================================================
TABLA 19
Dimensiones: (1, 4)

            0         1      2      3
0  Total time  09:43:46  53:44  03:39

## 12. Reconstrucción de la tabla completa de splits

HYRESULT divide los splits en varias tablas HTML. En este bloque las unimos en una única tabla.

In [95]:
from io import StringIO

def extraer_splits(url_resultado):

    url_splits = url_resultado + "?tab=splits"

    response = requests.get(url_splits, headers=headers)

    tablas = pd.read_html(StringIO(response.text))

    tablas_limpias = []

    for i, tabla in enumerate(tablas):

        if i == 0:
            tablas_limpias.append(tabla)

        else:

            tabla.columns = ["Split", "Time of Day", "Time", "Diff"]

            tablas_limpias.append(tabla)

    df_splits = pd.concat(tablas_limpias, ignore_index=True)

    return df_splits

In [96]:
url_resultado = df_categoria.loc[0, "analyze_url"]

df_splits = extraer_splits(url_resultado)

print("Número de filas:", len(df_splits))

display(df_splits)

Número de filas: 30

                    Split Time of Day   Time   Diff
0              Roxzone In    08:53:23  03:21  03:21
1               SkiErg In    08:53:26  03:23   0:02
2              SkiErg Out    08:57:25  07:23  04:00
3             Roxzone Out    08:57:28  07:25   0:02
4              Roxzone In    09:00:50  10:47  03:22
5            Sled Push In    09:01:02  11:00   0:13
6           Sled Push Out    09:03:10  13:07  02:07
7             Roxzone Out    09:03:13  13:11   0:04
8              Roxzone In    09:06:43  16:41  03:30
9            Sled Pull In    09:06:58  16:56   0:15
10          Sled Pull Out    09:09:51  19:48  02:52
11            Roxzone Out    09:10:02  19:59   0:11
12             Roxzone In    09:13:26  23:24  03:25
13   Burpee Broad Jump In    09:13:30  23:27   0:03
14  Burpee Broad Jump Out    09:15:45  25:42  02:15
15            Roxzone Out    09:16:09  26:07   0:25
16             Roxzone In    09:19:34  29:31  03:24
17                 Row In    09:19:38  29:35   0:04
18                Row Out    09:23:44  33:42  04:07
19            Roxzone Out    09:24:14  34:12   0:30
20             Roxzone In    09:27:39  37:36  03:24
21       Farmers Carry In    09:27:51  37:48   0:12
22      Farmers Carry Out    09:29:21  39:18  01:30
23            Roxzone Out    09:29:55  39:52   0:34
24             Roxzone In    09:33:16  43:13  03:21
25      Sandbag Lunges In    09:33:26  43:24   0:11
26     Sandbag Lunges Out    09:36:05  46:02  02:38
27            Roxzone Out    09:36:40  46:38   0:36
28          Wall Balls In    09:40:07  50:05  03:27
29             Total time    09:43:46  53:44  03:39

## 13. Función para extraer splits con identificador del atleta

Convertimos la extracción anterior en una función reutilizable. La función descarga la pestaña Splits de un atleta y añade sus datos identificativos.

In [97]:
def extraer_splits_atleta(fila_atleta):
    url_resultado = fila_atleta["analyze_url"]
    url_splits = url_resultado + "?tab=splits"

    response = requests.get(url_splits, headers=headers)

    tablas = pd.read_html(StringIO(response.text))

    tablas_limpias = []

    for i, tabla in enumerate(tablas):
        if i == 0:
            tabla.columns = ["Split", "Time of Day", "Time", "Diff"]
            tablas_limpias.append(tabla)
        else:
            tabla.columns = ["Split", "Time of Day", "Time", "Diff"]
            tablas_limpias.append(tabla)

    df_splits = pd.concat(tablas_limpias, ignore_index=True)

    df_splits["posicion"] = fila_atleta["posicion"]
    df_splits["nombre"] = fila_atleta["nombre"]
    df_splits["grupo_edad"] = fila_atleta["grupo_edad"]
    df_splits["pais"] = fila_atleta["pais"]
    df_splits["tiempo_total"] = fila_atleta["tiempo"]
    df_splits["analyze_url"] = fila_atleta["analyze_url"]

    return df_splits

In [98]:
df_splits_1 = extraer_splits_atleta(df_categoria.iloc[0])

print(df_splits_1.shape)

df_splits_1.head(10)

(30, 10)

,Split,Time of Day,Time,Diff,posicion,nombre,grupo_edad,pais,tiempo_total,analyze_url
0,Roxzone In,08:53:23,03:21,03:21,1,Gaetan Gianni,16-24,France,53:44,https://www.hyresult.com/result/LR3MS4JI502C48
1,SkiErg In,08:53:26,03:23,0:02,1,Gaetan Gianni,16-24,France,53:44,https://www.hyresult.com/result/LR3MS4JI502C48
2,SkiErg Out,08:57:25,07:23,04:00,1,Gaetan Gianni,16-24,France,53:44,https://www.hyresult.com/result/LR3MS4JI502C48
3,Roxzone Out,08:57:28,07:25,0:02,1,Gaetan Gianni,16-24,France,53:44,https://www.hyresult.com/result/LR3MS4JI502C48
4,Roxzone In,09:00:50,10:47,03:22,1,Gaetan Gianni,16-24,France,53:44,https://www.hyresult.com/result/LR3MS4JI502C48
5,Sled Push In,09:01:02,11:00,0:13,1,Gaetan Gianni,16-24,France,53:44,https://www.hyresult.com/result/LR3MS4JI502C48
6,Sled Push Out,09:03:10,13:07,02:07,1,Gaetan Gianni,16-24,France,53:44,https://www.hyresult.com/result/LR3MS4JI502C48
7,Roxzone Out,09:03:13,13:11,0:04,1,Gaetan Gianni,16-24,France,53:44,https://www.hyresult.com/result/LR3MS4JI502C48
8,Roxzone In,09:06:43,16:41,03:30,1,Gaetan Gianni,16-24,France,53:44,https://www.hyresult.com/result/LR3MS4JI502C48
9,Sled Pull In,09:06:58,16:56,0:15,1,Gaetan Gianni,16-24,France,53:44,https://www.hyresult.com/result/LR3MS4JI502C48

## 14. Prueba de extracción de splits para varios atletas

Antes de descargar todos los atletas, probamos la función con una muestra pequeña para comprobar que la estructura es estable.

In [99]:
# Probamos con los 5 primeros atletas

dfs_splits_prueba = []

for i in range(5):
    print("Extrayendo atleta", i + 1)

    df_temp = extraer_splits_atleta(df_categoria.iloc[i])
    dfs_splits_prueba.append(df_temp)

    time.sleep(0.5)

df_splits_prueba = pd.concat(dfs_splits_prueba, ignore_index=True)

print("Filas totales:", len(df_splits_prueba))

df_splits_prueba.head()

Extrayendo atleta 1
Extrayendo atleta 2
Extrayendo atleta 3
Extrayendo atleta 4
Extrayendo atleta 5
Filas totales: 150

,Split,Time of Day,Time,Diff,posicion,nombre,grupo_edad,pais,tiempo_total,analyze_url
0,Roxzone In,08:53:23,03:21,03:21,1,Gaetan Gianni,16-24,France,53:44,https://www.hyresult.com/result/LR3MS4JI502C48
1,SkiErg In,08:53:26,03:23,0:02,1,Gaetan Gianni,16-24,France,53:44,https://www.hyresult.com/result/LR3MS4JI502C48
2,SkiErg Out,08:57:25,07:23,04:00,1,Gaetan Gianni,16-24,France,53:44,https://www.hyresult.com/result/LR3MS4JI502C48
3,Roxzone Out,08:57:28,07:25,0:02,1,Gaetan Gianni,16-24,France,53:44,https://www.hyresult.com/result/LR3MS4JI502C48
4,Roxzone In,09:00:50,10:47,03:22,1,Gaetan Gianni,16-24,France,53:44,https://www.hyresult.com/result/LR3MS4JI502C48

## 15. Prueba ampliada con 50 atletas

Antes de descargar toda la categoría, probamos con 50 atletas para comprobar estabilidad y detectar posibles páginas sin splits o estructuras diferentes.

In [101]:
dfs_splits_50 = []
errores_splits = []

for i in range(50):
    fila = df_categoria.iloc[i]

    try:
        print(f"Extrayendo {i+1}/50: {fila['nombre']}")

        df_temp = extraer_splits_atleta(fila)
        dfs_splits_50.append(df_temp)

        time.sleep(0.5)

    except Exception as e:
        print(f"Error en {fila['nombre']}: {e}")

        errores_splits.append({
            "indice": i,
            "posicion": fila["posicion"],
            "nombre": fila["nombre"],
            "analyze_url": fila["analyze_url"],
            "error": str(e)
        })

df_splits_50 = pd.concat(dfs_splits_50, ignore_index=True)

print("Atletas con splits descargados:", df_splits_50["nombre"].nunique())
print("Filas totales:", len(df_splits_50))
print("Errores:", len(errores_splits))

df_splits_50.head()

Extrayendo 1/50: Gaetan Gianni
Extrayendo 2/50: Emilio Aguayo
Extrayendo 3/50: Loic Cebelieu
Extrayendo 4/50: Ferran Bochaca Sabarich
Extrayendo 5/50: Alberto Casado Aroca
Extrayendo 6/50: Sebastien Rajkowski
Extrayendo 7/50: Mehdi Berrouigat
Extrayendo 8/50: Pau Nacenta Merinas
Extrayendo 9/50: Aaron Timmerman
Extrayendo 10/50: Walter Paladina
Extrayendo 11/50: Ethan Smith
Extrayendo 12/50: Mohamed Yassin Kattar
Extrayendo 13/50: Yoel Ferrer
Extrayendo 14/50: Russell Christie
Extrayendo 15/50: Martin Casse
Extrayendo 16/50: James Francis
Extrayendo 17/50: Thomas Jurado
Extrayendo 18/50: Robert Stols
Extrayendo 19/50: Sam Booth
Extrayendo 20/50: David San Miguel López
Extrayendo 21/50: Xabier De Velasco
Extrayendo 22/50: Javier Puyalto Monaj
Extrayendo 23/50: Ivan Llorens Catala
Extrayendo 24/50: Sam Garcia
Extrayendo 25/50: John Murtagh
Extrayendo 26/50: Julien Caujolle
Extrayendo 27/50: Luis Caja Nacher
Extrayendo 28/50: Joost Huisink
Extrayendo 29/50: Yann Borderie
Extrayendo 30/50: Rodrigo de Zatarain Llaca
Extrayendo 31/50: Alex Lang
Extrayendo 32/50: Pepe Juangran
Extrayendo 33/50: Jordan Lynch
Extrayendo 34/50: Étienne Lite
Extrayendo 35/50: Gonzalo Espejo Del Rio
Extrayendo 36/50: Axel Solegre
Extrayendo 37/50: Alessandro Rossi
Extrayendo 38/50: Maxime Bonelli
Extrayendo 39/50: Ignacio Dañobeitia
Extrayendo 40/50: Richard Daniels
Extrayendo 41/50: Rubén García Carnicero
Extrayendo 42/50: Tomaž Gojčič
Extrayendo 43/50: Ansumana Konteh Sanneh
Extrayendo 44/50: Ian Michalik
Extrayendo 45/50: Marc Sadurni De La Torre
Extrayendo 46/50: Marcos Caballero Corral
Extrayendo 47/50: Theodore Golan
Extrayendo 48/50: Mikek Salgado Imaz
Extrayendo 49/50: Colin Davy
Extrayendo 50/50: Barney Fairnington
Atletas con splits descargados: 50
Filas totales: 1500
Errores: 0

,Split,Time of Day,Time,Diff,posicion,nombre,grupo_edad,pais,tiempo_total,analyze_url
0,Roxzone In,08:53:23,03:21,03:21,1,Gaetan Gianni,16-24,France,53:44,https://www.hyresult.com/result/LR3MS4JI502C48
1,SkiErg In,08:53:26,03:23,0:02,1,Gaetan Gianni,16-24,France,53:44,https://www.hyresult.com/result/LR3MS4JI502C48
2,SkiErg Out,08:57:25,07:23,04:00,1,Gaetan Gianni,16-24,France,53:44,https://www.hyresult.com/result/LR3MS4JI502C48
3,Roxzone Out,08:57:28,07:25,0:02,1,Gaetan Gianni,16-24,France,53:44,https://www.hyresult.com/result/LR3MS4JI502C48
4,Roxzone In,09:00:50,10:47,03:22,1,Gaetan Gianni,16-24,France,53:44,https://www.hyresult.com/result/LR3MS4JI502C48

In [102]:
df_splits_50.groupby("nombre")["Split"].count().sort_values()

nombre
Aaron Timmerman              30
Alberto Casado Aroca         30
Alessandro Rossi             30
Alex Lang                    30
Ansumana Konteh Sanneh       30
Axel Solegre                 30
Barney Fairnington           30
Colin Davy                   30
David San Miguel López       30
Emilio Aguayo                30
Ethan Smith                  30
Ferran Bochaca Sabarich      30
Gaetan Gianni                30
Gonzalo Espejo Del Rio       30
Ian Michalik                 30
Ignacio Dañobeitia           30
Ivan Llorens Catala          30
James Francis                30
Javier Puyalto Monaj         30
John Murtagh                 30
Joost Huisink                30
Jordan Lynch                 30
Julien Caujolle              30
Loic Cebelieu                30
Luis Caja Nacher             30
Marc Sadurni De La Torre     30
Marcos Caballero Corral      30
Martin Casse                 30
Maxime Bonelli               30
Mehdi Berrouigat             30
Mikek Salgado Imaz           30
Mohamed Yassin Kattar        30
Pau Nacenta Merinas          30
Pepe Juangran                30
Richard Daniels              30
Robert Stols                 30
Rodrigo de Zatarain Llaca    30
Rubén García Carnicero       30
Russell Christie             30
Sam Booth                    30
Sam Garcia                   30
Sebastien Rajkowski          30
Theodore Golan               30
Thomas Jurado                30
Tomaž Gojčič                 30
Walter Paladina              30
Xabier De Velasco            30
Yann Borderie                30
Yoel Ferrer                  30
Étienne Lite                 30
Name: Split, dtype: int64

In [104]:
df_categoria.to_csv("barcelona2026_hyrox_men_ranking.csv", index=False)

In [105]:
#DESCARGA COMPLETA
dfs_splits_todos = []
errores_splits_todos = []

for i in range(len(df_categoria)):
    fila = df_categoria.iloc[i]

    try:
        print(f"Extrayendo {i+1}/{len(df_categoria)}: {fila['nombre']}")

        df_temp = extraer_splits_atleta(fila)
        dfs_splits_todos.append(df_temp)

        time.sleep(0.5)

    except Exception as e:
        print(f"Error en {fila['nombre']}: {e}")

        errores_splits_todos.append({
            "indice": i,
            "posicion": fila["posicion"],
            "nombre": fila["nombre"],
            "analyze_url": fila["analyze_url"],
            "error": str(e)
        })

df_splits_todos = pd.concat(dfs_splits_todos, ignore_index=True)

print("Atletas con splits descargados:", df_splits_todos["nombre"].nunique())
print("Filas totales:", len(df_splits_todos))
print("Errores:", len(errores_splits_todos))

Extrayendo 1/2349: Gaetan Gianni
Extrayendo 2/2349: Emilio Aguayo
Extrayendo 3/2349: Loic Cebelieu
Extrayendo 4/2349: Ferran Bochaca Sabarich
Extrayendo 5/2349: Alberto Casado Aroca
Extrayendo 6/2349: Sebastien Rajkowski
Extrayendo 7/2349: Mehdi Berrouigat
Extrayendo 8/2349: Pau Nacenta Merinas
Extrayendo 9/2349: Aaron Timmerman
Extrayendo 10/2349: Walter Paladina
Extrayendo 11/2349: Ethan Smith
Extrayendo 12/2349: Mohamed Yassin Kattar
Extrayendo 13/2349: Yoel Ferrer
Extrayendo 14/2349: Russell Christie
Extrayendo 15/2349: Martin Casse
Extrayendo 16/2349: James Francis
Extrayendo 17/2349: Thomas Jurado
Extrayendo 18/2349: Robert Stols
Extrayendo 19/2349: Sam Booth
Extrayendo 20/2349: David San Miguel López
Extrayendo 21/2349: Xabier De Velasco
Extrayendo 22/2349: Javier Puyalto Monaj
Extrayendo 23/2349: Ivan Llorens Catala
Extrayendo 24/2349: Sam Garcia
Extrayendo 25/2349: John Murtagh
Extrayendo 26/2349: Julien Caujolle
Extrayendo 27/2349: Luis Caja Nacher
Extrayendo 28/2349: Joost Huisink
Extrayendo 29/2349: Yann Borderie
Extrayendo 30/2349: Rodrigo de Zatarain Llaca
Extrayendo 31/2349: Alex Lang
Extrayendo 32/2349: Pepe Juangran
Extrayendo 33/2349: Jordan Lynch
Extrayendo 34/2349: Étienne Lite
Extrayendo 35/2349: Gonzalo Espejo Del Rio
Extrayendo 36/2349: Axel Solegre
Extrayendo 37/2349: Alessandro Rossi
Extrayendo 38/2349: Maxime Bonelli
Extrayendo 39/2349: Ignacio Dañobeitia
Extrayendo 40/2349: Richard Daniels
Extrayendo 41/2349: Rubén García Carnicero
Extrayendo 42/2349: Tomaž Gojčič
Extrayendo 43/2349: Ansumana Konteh Sanneh
Extrayendo 44/2349: Ian Michalik
Extrayendo 45/2349: Marc Sadurni De La Torre
Extrayendo 46/2349: Marcos Caballero Corral
Extrayendo 47/2349: Theodore Golan
Extrayendo 48/2349: Mikek Salgado Imaz
Extrayendo 49/2349: Colin Davy
Extrayendo 50/2349: Barney Fairnington
Extrayendo 51/2349: Alvaro Monedero
Extrayendo 52/2349: Teun Alberts
Extrayendo 53/2349: Jules Chouvin
Extrayendo 54/2349: Matthieu Vanbaelinghem
Extrayendo 55/2349: Will Wellon
Extrayendo 56/2349: Aaron Cleaver
Extrayendo 57/2349: Jordan Noble
Extrayendo 58/2349: José Ramón Rodes Martinez
Extrayendo 59/2349: Ioannis Marinou
Extrayendo 60/2349: Steven Broxton
Extrayendo 61/2349: Manu Lacaba
Extrayendo 62/2349: Piripi Korent
Extrayendo 63/2349: Dylan Hobson
Extrayendo 64/2349: Sjors Lankhaar
Extrayendo 65/2349: Thomas Lorblanchet
Extrayendo 66/2349: Maxime Bordeaux
Extrayendo 67/2349: Corentin Loiseaux
Extrayendo 68/2349: Driss Alami
Extrayendo 69/2349: David Damjakob
Extrayendo 70/2349: Gerard Pericay Freixes
Extrayendo 71/2349: Thomas Capitani
Extrayendo 72/2349: Loris Thomas
Extrayendo 73/2349: Tom France
Extrayendo 74/2349: Sergi Garcia Magrans
Extrayendo 75/2349: Lewys Mccafferty
Extrayendo 76/2349: Matthieu Andujar
Extrayendo 77/2349: Pierrick Chaume
Extrayendo 78/2349: Mickael Braye
Extrayendo 79/2349: Kevin Horner
Extrayendo 80/2349: Lucas Parron Barcelona
Extrayendo 81/2349: Igor Rojo
Extrayendo 82/2349: Cormac Hannan
Extrayendo 83/2349: Juan Pajares
Extrayendo 84/2349: Marc Houngbedji
Extrayendo 85/2349: Robert Sobczak
Extrayendo 86/2349: Anthony Mendes
Extrayendo 87/2349: Paul Marleux
Extrayendo 88/2349: Ivan De Mora Martín
Extrayendo 89/2349: Eoghan O Murchu
Extrayendo 90/2349: Bernardo Neto
Extrayendo 91/2349: Alvaro Cardona
Extrayendo 92/2349: Clément Rojas
Extrayendo 93/2349: Alex Rowlands
Extrayendo 94/2349: Adham Hany
Extrayendo 95/2349: Mackenzie Heaney
Extrayendo 96/2349: Romain Marais
Extrayendo 97/2349: NICOLAS ALBERTO HERNANDEZ SANCHEZ
Extrayendo 98/2349: Luke Wise
Extrayendo 99/2349: Pierluigi Senor
Extrayendo 100/2349: Marceau Crayssac
Extrayendo 101/2349: Temoe Fels
Extrayendo 102/2349: Maxime Renard
Extrayendo 103/2349: Nils Lombard
Extrayendo 104/2349: Javier Carmona  Mansilla
Extrayendo 105/2349: Alejandro Vera Blanco
Extrayendo 106/2349: Nahuel Galván
Extrayendo 107/2349: Marc Guillazo
Extrayendo 108/2349: Nicolas LITCHMAN
Extrayendo 109/2349: Felix Casalod
Extrayendo 110/2349: Richard Gill
Extrayendo 111/2349: Victor Peña
Extrayendo 112/2349: Bastien Nugon
Extrayendo 113/2349: Sebastian Fernández Espinoza De Los Mont
Extrayendo 114/2349: Ben Parry
Extrayendo 115/2349: Paraic Hannan
Extrayendo 116/2349: Kaveh Farahmand
Extrayendo 117/2349: Guillaume Chusseau
Extrayendo 118/2349: Nicolas Darrieutort
Extrayendo 119/2349: Juan Antonio Arenas
Extrayendo 120/2349: Bixente Orance
Extrayendo 121/2349: Daniel Johnson
Extrayendo 122/2349: Santi Valle
Extrayendo 123/2349: Tiler Jones
Extrayendo 124/2349: Ben Whittaker
Extrayendo 125/2349: Diogo Rodrigues
Extrayendo 126/2349: Jonathan Escribano Arjona
Extrayendo 127/2349: Jonathan Eames
Extrayendo 128/2349: Peter Zuravlev
Extrayendo 129/2349: Davide Marone
Extrayendo 130/2349: Guillaume Jolly
Extrayendo 131/2349: Nathan Pierre
Extrayendo 132/2349: Janis Burkhart
Extrayendo 133/2349: Yvan Cina
Extrayendo 134/2349: Rafa Morgado
Extrayendo 135/2349: Harvey Jones
Extrayendo 136/2349: Rob Amor
Extrayendo 137/2349: Owen Mccue
Extrayendo 138/2349: Alex Iloie
Extrayendo 139/2349: David Delgado
Extrayendo 140/2349: Jorge Bartolomé Rodríguez
Extrayendo 141/2349: Oscar Cerezuela
Extrayendo 142/2349: Paul Wolf
Extrayendo 143/2349: James Lang
Extrayendo 144/2349: Vincent Ferré
Extrayendo 145/2349: Ahmed Alhashmi
Extrayendo 146/2349: Heros Iapello
Extrayendo 147/2349: Morgan O Donoghue
Extrayendo 148/2349: Eoghan Daly
Extrayendo 149/2349: Harry Behrens
Extrayendo 150/2349: Fernando Pajares
Extrayendo 151/2349: Cyril Benech
Extrayendo 152/2349: Marcos Palomero
Extrayendo 153/2349: Teo Arasa Cid
Extrayendo 154/2349: Joshua Drake
Extrayendo 155/2349: Ross Mcgarry
Extrayendo 156/2349: João Matos
Extrayendo 157/2349: Ralph Walker-Moretti
Extrayendo 158/2349: Miguel Franco Ruas
Extrayendo 159/2349: Alexandre Viala
Extrayendo 160/2349: Aaron Cullen
Extrayendo 161/2349: Tom Woods
Extrayendo 162/2349: Matthias Duelund Pedersen
Extrayendo 163/2349: Enric Costa Torrents
Extrayendo 164/2349: Thibault Boullé
Extrayendo 165/2349: Adrián Bonilla
Extrayendo 166/2349: Guillem Sanchis
Extrayendo 167/2349: Feliu Coronado
Extrayendo 168/2349: Paul Cérantola
Extrayendo 169/2349: Jack Forrester
Extrayendo 170/2349: Iñaki Gonzalez Veintemillas
Extrayendo 171/2349: Arturo Oliva
Extrayendo 172/2349: Roberto Reina
Extrayendo 173/2349: Théo Valero
Extrayendo 174/2349: Pablo Moraga
Extrayendo 175/2349: Ausaine Konteh Sanneh
Extrayendo 176/2349: Toni Horcajada Lopez
Extrayendo 177/2349: Alex Rodiera
Extrayendo 178/2349: Simon Raeyen
Extrayendo 179/2349: Carlos Pajares
Extrayendo 180/2349: Haritz Blanco Bello
Extrayendo 181/2349: Matt Burford
Extrayendo 182/2349: Claret Rosset
Extrayendo 183/2349: Pablo Calvo Iborra
Extrayendo 184/2349: Teddy Mallet
Extrayendo 185/2349: Zackary Gueddari
Extrayendo 186/2349: Jiří Skácelík
Extrayendo 187/2349: Szymon Mochnacz
Extrayendo 188/2349: Ladjie Niakate
Extrayendo 189/2349: Alejandro Morón Castillo
Extrayendo 190/2349: Arno Herssens
Extrayendo 191/2349: Nathaniel Morris
Extrayendo 192/2349: RUI PEDRO SILVA
Extrayendo 193/2349: Mohammad Jafar
Extrayendo 194/2349: Evan Collumbine
Extrayendo 195/2349: Jonathan Delbert
Extrayendo 196/2349: Victor Peña Gomez
Extrayendo 197/2349: Christopher Harger
Extrayendo 198/2349: Dawid Andrzej Mwila
Extrayendo 199/2349: Jose Martinez
Extrayendo 200/2349: James Pyne
Extrayendo 201/2349: Ramón Gutiérrez Sánchez
Extrayendo 202/2349: Ruben Oliveira
Extrayendo 203/2349: William Matthews
Extrayendo 204/2349: Nathan Condon
Extrayendo 205/2349: Edoardo Nodaro
Extrayendo 206/2349: Jérémie Guenole
Extrayendo 207/2349: Gorka Sanchez
Extrayendo 208/2349: Oscar Valentin Garcia
Extrayendo 209/2349: Joshua Scott
Extrayendo 210/2349: Tom Stewart
Extrayendo 211/2349: Jose Miguel Lopez Sanchez
Extrayendo 212/2349: Julien Ponti
Extrayendo 213/2349: Marvin Patras
Extrayendo 214/2349: Javier Russo
Extrayendo 215/2349: Ivan Lanceta
Extrayendo 216/2349: Lucas Ait Benamara
Extrayendo 217/2349: Diony Torrero
Extrayendo 218/2349: Dan Thomas
Extrayendo 219/2349: Alban Soulié
Extrayendo 220/2349: Ivan Bailach
Extrayendo 221/2349: Eric Infante Garcia
Extrayendo 222/2349: André Agostinho
Extrayendo 223/2349: Mette Stam
Extrayendo 224/2349: Nicolas Boissy
Extrayendo 225/2349: Unai Cruz
Extrayendo 226/2349: Bruno Ramos
Extrayendo 227/2349: Nicolas Landes
Extrayendo 228/2349: Marc Domenjó
Extrayendo 229/2349: Charly Bertrand
Extrayendo 230/2349: Micael Vieira
Extrayendo 231/2349: James Cahalane
Extrayendo 232/2349: Austyn Hardy
Extrayendo 233/2349: Aleix Felip
Extrayendo 234/2349: Lorin Martinez
Extrayendo 235/2349: Nico Plück
Extrayendo 236/2349: Edgar Sundt
Extrayendo 237/2349: Juan Julián Morcillo González
Extrayendo 238/2349: Roger Farré
Extrayendo 239/2349: Darren Williscroft
Extrayendo 240/2349: Jack Redfern
Extrayendo 241/2349: Fabio Lorenzon
Extrayendo 242/2349: Josh Carrigan
Extrayendo 243/2349: Robin Deslandes
Extrayendo 244/2349: Jean-Baptiste Grimal
Extrayendo 245/2349: Robbie Clyne
Extrayendo 246/2349: Vincent Gibert
Extrayendo 247/2349: Sascha Rohner
Extrayendo 248/2349: Biagio Rubinaccio
Extrayendo 249/2349: Josu Gilen Hualde
Extrayendo 250/2349: Rémi Pauly
Extrayendo 251/2349: Pablo Gomis De Gabriel
Extrayendo 252/2349: Matt Griffiths
Extrayendo 253/2349: Kevin Walter
Extrayendo 254/2349: Alejandro Esteban Loza
Extrayendo 255/2349: Cristian Costa
Extrayendo 256/2349: Sergi Saez
Extrayendo 257/2349: Olivier Beugin
Extrayendo 258/2349: Pau Aguiló  Mayol
Extrayendo 259/2349: Mathias Maxa
Extrayendo 260/2349: Jordan Auvergne
Extrayendo 261/2349: Remco Waanders
Extrayendo 262/2349: Nicolas Coppet
Extrayendo 263/2349: James Russell
Extrayendo 264/2349: Rui Leite
Extrayendo 265/2349: Ross Walker
Extrayendo 266/2349: Henry Hodge
Extrayendo 267/2349: Cedric Puaud
Extrayendo 268/2349: Zach Calnan
Extrayendo 269/2349: Craig Douglas
Extrayendo 270/2349: Adrian Enright
Extrayendo 271/2349: Alex Parmentier
Extrayendo 272/2349: Andrew Shields
Extrayendo 273/2349: Antonio Illan Garcia
Extrayendo 274/2349: Tomás Leal
Extrayendo 275/2349: Benjamin Martinez
Extrayendo 276/2349: Sergi Rubio
Extrayendo 277/2349: Tanguy Martin
Extrayendo 278/2349: Bastien Etcheverria
Extrayendo 279/2349: Eric Sendas
Extrayendo 280/2349: Enrico Ticoalu
Extrayendo 281/2349: Karol Kutta
Extrayendo 282/2349: Tera Tapao
Extrayendo 283/2349: Josh Harper
Extrayendo 284/2349: Mauro Grioli
Extrayendo 285/2349: Lorenzo Resta
Extrayendo 286/2349: Mario Dieste Ballarin
Extrayendo 287/2349: Ellis Wiffen
Extrayendo 288/2349: Fernando Arias
Extrayendo 289/2349: Guillermo Fernandez Moraleda
Extrayendo 290/2349: Daniele Cotti
Extrayendo 291/2349: Jose Antonio Martin Quiroga
Extrayendo 292/2349: Anthony Laborde
Extrayendo 293/2349: Sergio Turull
Extrayendo 294/2349: Willem Ballet
Extrayendo 295/2349: Maxime Larramendy
Extrayendo 296/2349: Benjamin Bruns
Extrayendo 297/2349: David Saus
Extrayendo 298/2349: Manuel Valtulini
Extrayendo 299/2349: Max Myers
Extrayendo 300/2349: Aurelien Gedon
Extrayendo 301/2349: Matt Kelly
Extrayendo 302/2349: Obiora Onuora
Extrayendo 303/2349: Samson Brown
Extrayendo 304/2349: Theo Ferin
Extrayendo 305/2349: Jesús Guillén
Extrayendo 306/2349: Jack Rea
Extrayendo 307/2349: Tristan Le Moing
Extrayendo 308/2349: Christian Göller
Extrayendo 309/2349: Timm Ehret
Extrayendo 310/2349: Darren Morgan
Extrayendo 311/2349: Roger Cayuela
Extrayendo 312/2349: Omar Eissa
Extrayendo 313/2349: Juan Gómez Miralles
Extrayendo 314/2349: Emmanuel Quemerais
Extrayendo 315/2349: Rowen Koot
Extrayendo 316/2349: Mickael Guignard
Extrayendo 317/2349: Ewen Cheval
Extrayendo 318/2349: Fabian Althammer
Extrayendo 319/2349: Carlos Ruiz Manuel
Extrayendo 320/2349: Yoan Gomez
Extrayendo 321/2349: Davide Nappo
Extrayendo 322/2349: Philipp Ströming
Extrayendo 323/2349: Callum Keavey
Extrayendo 324/2349: Lluis Pons Pons
Extrayendo 325/2349: David Fernández
Extrayendo 326/2349: Niall Clinton
Extrayendo 327/2349: Faustas Stoncius
Extrayendo 328/2349: Richard Burrows
Extrayendo 329/2349: Sam Armand
Extrayendo 330/2349: Ruben Torrado Nogales
Extrayendo 331/2349: Evan Morvan
Extrayendo 332/2349: Steven Copeland
Extrayendo 333/2349: Gabriel Fleury
Extrayendo 334/2349: Francesco Borsari
Extrayendo 335/2349: Daniel Knox
Extrayendo 336/2349: Martin Hoffmann
Extrayendo 337/2349: Mariano Ramis
Extrayendo 338/2349: Dominykas Jutas
Extrayendo 339/2349: Jordi Bonet Domínguez
Extrayendo 340/2349: Isaac Backhouse
Extrayendo 341/2349: Maximilian Delakowitz
Extrayendo 342/2349: Jason Albon
Extrayendo 343/2349: Ed Miles
Extrayendo 344/2349: Jesus Aguado Agenjo
Extrayendo 345/2349: Tiago Cristo
Extrayendo 346/2349: Justyn Mckay
Extrayendo 347/2349: Sandro Hörler
Extrayendo 348/2349: Marco Grübl
Extrayendo 349/2349: Jesus Baquedano Mozos
Extrayendo 350/2349: Toni Gilart
Extrayendo 351/2349: Sébastien Garro
Extrayendo 352/2349: Loic Gironde
Extrayendo 353/2349: Luis Maggio
Extrayendo 354/2349: Ricardo Goizueta
Extrayendo 355/2349: Matthew Moslenko
Extrayendo 356/2349: Álvaro Crespo Maeztu
Extrayendo 357/2349: Meinhard Meintjes
Extrayendo 358/2349: Jonathan Cody
Extrayendo 359/2349: Lloyd Echegaray Frances
Extrayendo 360/2349: Kevin Nino
Extrayendo 361/2349: Nate B
Extrayendo 362/2349: Marc Gunter
Extrayendo 363/2349: Mateus Saraiva
Extrayendo 364/2349: Hugo Barros Alonso
Extrayendo 365/2349: Frédérick Fisson
Extrayendo 366/2349: Aaron Zahra
Extrayendo 367/2349: Armando Silva
Extrayendo 368/2349: Ruben Beltran
Extrayendo 369/2349: Pablo Fernandez Cañete
Extrayendo 370/2349: Aurélien Artinian
Extrayendo 371/2349: Thomas Arcas
Extrayendo 372/2349: Aidan Hyland
Extrayendo 373/2349: Alexis Emanuel Olivares
Extrayendo 374/2349: Alexandre Kong
Extrayendo 375/2349: Jacob Gratton
Extrayendo 376/2349: Cyril Puech
Extrayendo 377/2349: Álvaro Torres
Extrayendo 378/2349: Simao Saraiva
Extrayendo 379/2349: Florent Besombes
Extrayendo 380/2349: Joey Van De Kerkhof
Extrayendo 381/2349: Andy Br
Extrayendo 382/2349: Marc Ollé
Extrayendo 383/2349: Joel Perez Valencia
Extrayendo 384/2349: Guillaume Clert
Extrayendo 385/2349: Jack Scully
Extrayendo 386/2349: Ivan Serrano
Extrayendo 387/2349: Kylane Ait Hamou
Extrayendo 388/2349: Borja Sepulveda
Extrayendo 389/2349: Fernando Gurrea
Extrayendo 390/2349: Alessandro Benedetti
Extrayendo 391/2349: Joan Carles Castella
Extrayendo 392/2349: Kevin Labaume
Extrayendo 393/2349: Sascha Dewald
Extrayendo 394/2349: David Gomtsyan
Extrayendo 395/2349: Glen Preibisch Lecha
Extrayendo 396/2349: Mathias Saal
Extrayendo 397/2349: Guillem Rives
Extrayendo 398/2349: Phil Schwarick
Extrayendo 399/2349: Christian Saylor
Extrayendo 400/2349: Gaëtan Lopez
Extrayendo 401/2349: Luca Delgrosso
Extrayendo 402/2349: Max Smith
Extrayendo 403/2349: Troy Rouse
Extrayendo 404/2349: Mehdi Sabiri
Extrayendo 405/2349: Manyacca Menyoli
Extrayendo 406/2349: Marcos Aguilar Finez
Extrayendo 407/2349: Cédric Mazenq
Extrayendo 408/2349: Adrián Tello Beneit
Extrayendo 409/2349: Mickael Pascual
Extrayendo 410/2349: Clement Sarrat
Extrayendo 411/2349: Rob Worthington
Extrayendo 412/2349: Dan Addis
Extrayendo 413/2349: Théophile Deffrennes
Extrayendo 414/2349: Angel Pinilla Ciria
Extrayendo 415/2349: Eduardo Sánchez
Extrayendo 416/2349: Robert Baczewski
Extrayendo 417/2349: Christopher Roseau
Extrayendo 418/2349: Jens Weipert
Extrayendo 419/2349: Mathieu Peyris
Extrayendo 420/2349: António Piçarra
Extrayendo 421/2349: Jahmal Howlett-Mundle
Extrayendo 422/2349: Manuel Rizzetto
Extrayendo 423/2349: Johan Billoud
Extrayendo 424/2349: Hector Diaz
Extrayendo 425/2349: Ángel Fernández
Extrayendo 426/2349: Florian Preiss
Extrayendo 427/2349: John Hallopé
Extrayendo 428/2349: Jonny Sasati
Extrayendo 429/2349: Sebastian Harris
Extrayendo 430/2349: Pablo Anitua Diez
Extrayendo 431/2349: Karl Yelland
Extrayendo 432/2349: Rubén David Del Pino Serrano
Extrayendo 433/2349: Fernando Tena
Extrayendo 434/2349: Jamie Randall
Extrayendo 435/2349: James Bidwell
Extrayendo 436/2349: Niall Goodwin
Extrayendo 437/2349: Roy Céansu
Extrayendo 438/2349: Liam Mcclure
Extrayendo 439/2349: Tom Starling
Extrayendo 440/2349: Sam Draper
Extrayendo 441/2349: Jeremy Outmanns
Extrayendo 442/2349: Angel De Las Heras Lopez
Extrayendo 443/2349: Edward Whelan
Extrayendo 444/2349: Nicholas Abbott
Extrayendo 445/2349: Ilja Feilinger
Extrayendo 446/2349: Alan Cusack
Extrayendo 447/2349: Antoine Aldebert
Extrayendo 448/2349: Niclas Blåklinth
Extrayendo 449/2349: Guido Viggiani
Extrayendo 450/2349: Amadeo Villar Guardia
Extrayendo 451/2349: Sönke Weber
Extrayendo 452/2349: Ugo Porta
Extrayendo 453/2349: Veit Florian Kopenec
Extrayendo 454/2349: Bo Evertse
Extrayendo 455/2349: Javi Penadés
Extrayendo 456/2349: Julien Affre
Extrayendo 457/2349: Tom Darneix
Extrayendo 458/2349: Mikel Tamayo
Extrayendo 459/2349: Dan Harding
Extrayendo 460/2349: Luis Moyano Fernandez
Extrayendo 461/2349: Jaromír Täuber
Extrayendo 462/2349: Ignacio Mazon
Extrayendo 463/2349: Joris Harink
Extrayendo 464/2349: Reece Jefferson
Extrayendo 465/2349: Imad Chakor Djelthia
Extrayendo 466/2349: Liam White
Extrayendo 467/2349: Mickael Benyamina
Extrayendo 468/2349: Christian Perini
Extrayendo 469/2349: Enric Arbós Reyes
Extrayendo 470/2349: Sam Morley
Extrayendo 471/2349: Kevin Mansuy
Extrayendo 472/2349: Mateusz Zwierz
Extrayendo 473/2349: Stephen Maher
Extrayendo 474/2349: Anton Kostenzer
Extrayendo 475/2349: Marlon Duque
Extrayendo 476/2349: Federico Tonin
Extrayendo 477/2349: Julien Richalet
Extrayendo 478/2349: Patxi Mikel Triguero
Extrayendo 479/2349: Guillaume Cado
Extrayendo 480/2349: Nathan Poulet
Extrayendo 481/2349: Yoann Le Guen
Extrayendo 482/2349: Joshua Dams
Extrayendo 483/2349: Pablo Romero
Extrayendo 484/2349: mickael cavailles
Extrayendo 485/2349: Jo Curutchague
Extrayendo 486/2349: Kyle O'Donoghue
Extrayendo 487/2349: Joshua Moss
Extrayendo 488/2349: Stig René Bersaas Oldervik
Extrayendo 489/2349: Callum Tusler
Extrayendo 490/2349: Marco Vitoria Fagnani
Extrayendo 491/2349: David Hermo Blanco
Extrayendo 492/2349: Sergi Ayala
Extrayendo 493/2349: Mathias Bonis
Extrayendo 494/2349: Diego Zamorano Villar
Extrayendo 495/2349: Vincent Guillard
Extrayendo 496/2349: Aleksandar Stanev
Extrayendo 497/2349: Alvaro Vicente
Extrayendo 498/2349: Antonio Sanchez Gea
Extrayendo 499/2349: Antonio Casas
Extrayendo 500/2349: Luke Page
Extrayendo 501/2349: Simon Phillips
Extrayendo 502/2349: Sean Haughey
Extrayendo 503/2349: Simone Enrici
Extrayendo 504/2349: Charles Arsendaux
Extrayendo 505/2349: Nicolas Berruet
Extrayendo 506/2349: Stephane Pereira
Extrayendo 507/2349: Zach Shellman
Extrayendo 508/2349: Ricardo Martinez
Extrayendo 509/2349: Hugo Richomme
Extrayendo 510/2349: Paweł Studniarek
Extrayendo 511/2349: Oscar Aguilar Illana
Extrayendo 512/2349: Pedro Gonçalves
Extrayendo 513/2349: Ángel Caravaca Huertas
Extrayendo 514/2349: Amir Shkodra
Extrayendo 515/2349: Samuel Osmond
Extrayendo 516/2349: Matheo Gouley
Extrayendo 517/2349: Javier Altable
Extrayendo 518/2349: Rémi Jaunet
Extrayendo 519/2349: Lukas Kaspar
Extrayendo 520/2349: Samuel O'Sullivan
Extrayendo 521/2349: András Obsuszt
Extrayendo 522/2349: Gaetan Grau
Extrayendo 523/2349: Petros Kalodimos
Extrayendo 524/2349: Valentin Dorbes
Extrayendo 525/2349: Niklas Schurig
Extrayendo 526/2349: Manuel Oton Gallardo
Extrayendo 527/2349: Domingo Aguilera
Extrayendo 528/2349: Sergiu Olteanu
Extrayendo 529/2349: Nicolas Lespiauc
Extrayendo 530/2349: Enzo Perez
Extrayendo 531/2349: Samuele Monari
Extrayendo 532/2349: Jesse Van Krimpen
Extrayendo 533/2349: Ricardo Pillay
Extrayendo 534/2349: Miguel Hernandez
Extrayendo 535/2349: Nestor Atienza
Extrayendo 536/2349: Nik Vrešnjak
Extrayendo 537/2349: Erwan Daniel
Extrayendo 538/2349: Daniel Martin Ridruejo
Extrayendo 539/2349: Patrick Moloney
Extrayendo 540/2349: Kris Burns
Extrayendo 541/2349: Adrian Ojeda Almenar
Extrayendo 542/2349: Matis Cabrita
Extrayendo 543/2349: Przemysław Kopeć
Extrayendo 544/2349: Marc Chappelle
Extrayendo 545/2349: Nathan Hawkins
Extrayendo 546/2349: Darío Olivares
Extrayendo 547/2349: Luca Fiorani
Extrayendo 548/2349: Eric Harmsen
Extrayendo 549/2349: Juan Manuel Vellerino Garcia

In [106]:
df_splits_todos.to_csv("barcelona2026_hyrox_men_splits.csv", index=False)