<a href="https://colab.research.google.com/github/JaimeTS/hyrox-analysis/blob/main/notebooks/01_scraping_hyrox_limpio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Scraping de resultados HYROX

Objetivo: descargar los resultados de una prueba concreta desde HyResult y convertirlos en una base de datos estructurada para análisis de rendimiento, pacing y diferencias por edad y sexo.

ORDEN PARA DESCARGAR LOS DATOS.

Para todos hay que seguir el siguiente orden.

TODOS: Ejecutar el bloque completo

HOMBRES: 1-3 + 4

MUJERES: 1-3 + 5 (no el 4)

1. Librerías y configuración
2. Funciones generales
   2.1 extraer_ranking_pagina()
   2.2 descargar_categoria_completa()
   2.3 extraer_splits_atleta()
   2.4 descargar_splits_categoria()

3. Parámetros del evento

4. HYROX Men Barcelona 2026
   4.1 Ranking hombres
   4.2 Splits hombres

5. HYROX Women Barcelona 2026
   5.1 Ranking mujeres
   5.2 Splits mujeres

6. Unión Men + Women (opcional)

## 1. Librerías y configuración

In [1]:
import os
import math
import time
from io import StringIO

import requests
import pandas as pd
from bs4 import BeautifulSoup

BASE_URL = "https://www.hyresult.com"

headers = {
    "User-Agent": "Mozilla/5.0"
}

RUTA_DATOS = "/content/drive/MyDrive/Colab Notebooks/Hyrox"

os.makedirs(RUTA_DATOS, exist_ok=True)

## 2. Funciones generales

### 2.1 Función para extraer una página del ranking

In [2]:
def extraer_ranking_pagina(url):
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")

    rows = soup.find_all("tr")
    resultados = []

    i = 0

    while i < len(rows):
        cells = rows[i].find_all("td")
        textos = [c.get_text(" ", strip=True) for c in cells]

        # ==========================================================
        # CASO NORMAL
        # ==========================================================
        if len(cells) >= 7:

            posicion = cells[1].get_text(strip=True)
            posicion_ag = cells[2].get_text(strip=True)

            name_cell = cells[3]
            link_athlete = name_cell.find("a")
            img_flag = name_cell.find("img")

            nombre = link_athlete.get_text(strip=True) if link_athlete else None
            athlete_url = (
                link_athlete["href"]
                if link_athlete and link_athlete.has_attr("href")
                else None
            )

            pais = (
                img_flag["title"]
                if img_flag and img_flag.has_attr("title")
                else None
            )

            grupo_edad = cells[4].get_text(strip=True)
            tiempo = cells[5].get_text(strip=True)

            analyze_link = cells[6].find("a")
            analyze_url = (
                analyze_link["href"]
                if analyze_link and analyze_link.has_attr("href")
                else None
            )

            if nombre and tiempo and analyze_url:

                resultados.append({
                    "posicion": posicion,
                    "posicion_grupo_edad": posicion_ag,
                    "nombre": nombre,
                    "pais": pais,
                    "grupo_edad": grupo_edad,
                    "tiempo": tiempo,
                    "athlete_url": athlete_url,
                    "analyze_url": analyze_url
                })

            i += 1
            continue

        # ==========================================================
        # CASO ESPECIAL A
        # ==========================================================
        if len(cells) >= 3 and i + 4 < len(rows):

            posicion = cells[1].get_text(strip=True)
            posicion_ag = cells[2].get_text(strip=True)

            row_nombre = rows[i + 1]
            row_grupo = rows[i + 2]
            row_tiempo = rows[i + 3]
            row_analyze = rows[i + 4]

            nombre_cell = row_nombre.find("td")
            link_athlete = nombre_cell.find("a") if nombre_cell else None
            img_flag = nombre_cell.find("img") if nombre_cell else None

            nombre = link_athlete.get_text(strip=True) if link_athlete else None
            athlete_url = (
                link_athlete["href"]
                if link_athlete and link_athlete.has_attr("href")
                else None
            )

            pais = (
                img_flag["title"]
                if img_flag and img_flag.has_attr("title")
                else None
            )

            grupo_edad = row_grupo.get_text(" ", strip=True)
            tiempo = row_tiempo.get_text(" ", strip=True)

            analyze_link = row_analyze.find("a")
            analyze_url = (
                analyze_link["href"]
                if analyze_link and analyze_link.has_attr("href")
                else None
            )

            if nombre and tiempo and analyze_url:

                resultados.append({
                    "posicion": posicion,
                    "posicion_grupo_edad": posicion_ag,
                    "nombre": nombre,
                    "pais": pais,
                    "grupo_edad": grupo_edad,
                    "tiempo": tiempo,
                    "athlete_url": athlete_url,
                    "analyze_url": analyze_url
                })

                i += 5
                continue

        # ==========================================================
        # CASO ESPECIAL C
        # (fila vacía + datos repartidos)
        # ==========================================================
        if len(cells) == 1 and textos == [""] and i + 6 < len(rows):

            row_pos = rows[i + 1]
            row_pos_ag = rows[i + 2]
            row_nombre = rows[i + 3]
            row_grupo = rows[i + 4]
            row_tiempo = rows[i + 5]
            row_analyze = rows[i + 6]

            posicion = row_pos.get_text(" ", strip=True)
            posicion_ag = row_pos_ag.get_text(" ", strip=True)
            nombre = row_nombre.get_text(" ", strip=True)
            grupo_edad = row_grupo.get_text(" ", strip=True)
            tiempo = row_tiempo.get_text(" ", strip=True)

            analyze_link = row_analyze.find("a")
            analyze_url = (
                analyze_link["href"]
                if analyze_link and analyze_link.has_attr("href")
                else None
            )

            if (
                posicion.isdigit()
                and posicion_ag.isdigit()
                and nombre
                and tiempo
                and analyze_url
            ):

                resultados.append({
                    "posicion": posicion,
                    "posicion_grupo_edad": posicion_ag,
                    "nombre": nombre,
                    "pais": None,
                    "grupo_edad": grupo_edad,
                    "tiempo": tiempo,
                    "athlete_url": None,
                    "analyze_url": analyze_url
                })

                i += 7
                continue

        # ==========================================================
        # CASO ESPECIAL B
        # ==========================================================
        if len(cells) >= 2 and i + 5 < len(rows):

            posicion = cells[1].get_text(strip=True)

            row_pos_ag = rows[i + 1]
            row_nombre = rows[i + 2]
            row_grupo = rows[i + 3]
            row_tiempo = rows[i + 4]
            row_analyze = rows[i + 5]

            posicion_ag = row_pos_ag.get_text(" ", strip=True)

            nombre_cell = row_nombre.find("td")
            link_athlete = nombre_cell.find("a") if nombre_cell else None
            img_flag = nombre_cell.find("img") if nombre_cell else None

            nombre = link_athlete.get_text(strip=True) if link_athlete else None
            athlete_url = (
                link_athlete["href"]
                if link_athlete and link_athlete.has_attr("href")
                else None
            )

            pais = (
                img_flag["title"]
                if img_flag and img_flag.has_attr("title")
                else None
            )

            grupo_edad = row_grupo.get_text(" ", strip=True)
            tiempo = row_tiempo.get_text(" ", strip=True)

            analyze_link = row_analyze.find("a")
            analyze_url = (
                analyze_link["href"]
                if analyze_link and analyze_link.has_attr("href")
                else None
            )

            if nombre and tiempo and analyze_url:

                resultados.append({
                    "posicion": posicion,
                    "posicion_grupo_edad": posicion_ag,
                    "nombre": nombre,
                    "pais": pais,
                    "grupo_edad": grupo_edad,
                    "tiempo": tiempo,
                    "athlete_url": athlete_url,
                    "analyze_url": analyze_url
                })

                i += 6
                continue

        i += 1

    df = pd.DataFrame(resultados)

    if len(df) > 0:

        df["athlete_url"] = df["athlete_url"].apply(
            lambda x: BASE_URL + x if isinstance(x, str) and x.startswith("/") else x
        )

        df["analyze_url"] = df["analyze_url"].apply(
            lambda x: BASE_URL + x if isinstance(x, str) and x.startswith("/") else x
        )

    return df

### 2.2 Función para descargar una categoría completa

In [3]:
def descargar_categoria_completa(ranking_url, total_atletas, pausa=0.5):
    participantes_por_pagina = 100
    num_paginas = math.ceil(total_atletas / participantes_por_pagina)

    dfs = []

    for pagina in range(1, num_paginas + 1):
        url = f"{ranking_url}?p={pagina}"

        print(f"Descargando página {pagina}/{num_paginas}")

        df_pagina = extraer_ranking_pagina(url)
        dfs.append(df_pagina)

        time.sleep(pausa)

    df_categoria = pd.concat(dfs, ignore_index=True)

    return df_categoria

### 2.3 Función robusta para extraer splits

In [4]:
def extraer_splits_atleta(fila_atleta):
    url_resultado = fila_atleta["analyze_url"]
    url_splits = url_resultado + "?tab=splits"

    response = requests.get(url_splits, headers=headers)

    tablas = pd.read_html(StringIO(response.text))

    tablas_limpias = []

    for tabla in tablas:
        if tabla.shape[1] != 4:
            continue

        tabla = tabla.copy()
        tabla.columns = ["Split", "Time of Day", "Time", "Diff"]

        tabla = tabla.dropna(how="all")
        tabla = tabla[tabla["Split"].astype(str) != "Split"]

        tablas_limpias.append(tabla)

    if len(tablas_limpias) == 0:
        raise ValueError("No se encontraron tablas válidas de splits")

    df_splits = pd.concat(tablas_limpias, ignore_index=True)

    df_splits["posicion"] = fila_atleta["posicion"]
    df_splits["nombre"] = fila_atleta["nombre"]
    df_splits["grupo_edad"] = fila_atleta["grupo_edad"]
    df_splits["pais"] = fila_atleta["pais"]
    df_splits["tiempo_total"] = fila_atleta["tiempo"]
    df_splits["analyze_url"] = fila_atleta["analyze_url"]

    return df_splits

### 2.4 Función para descargar splits de una categoría

In [5]:
def descargar_splits_categoria(df_categoria, pausa=0.5):
    dfs_splits = []
    errores = []

    for i in range(len(df_categoria)):
        fila = df_categoria.iloc[i]

        try:
            print(f"Extrayendo {i+1}/{len(df_categoria)}: {fila['nombre']}")

            df_temp = extraer_splits_atleta(fila)
            dfs_splits.append(df_temp)

            time.sleep(pausa)

        except Exception as e:
            print(f"Error en {fila['nombre']}: {e}")

            errores.append({
                "indice": i,
                "posicion": fila["posicion"],
                "nombre": fila["nombre"],
                "analyze_url": fila["analyze_url"],
                "error": str(e)
            })

    df_splits = pd.concat(dfs_splits, ignore_index=True)
    df_errores = pd.DataFrame(errores)

    return df_splits, df_errores

## 3. Parámetros del evento

In [6]:
evento = "barcelona2026"

categorias = {
    "men": {
        "ranking_url": "https://www.hyresult.com/ranking/s8-2026-barcelona-hyrox-men",
        "total_atletas": 2350
    },
    "women": {
        "ranking_url": "https://www.hyresult.com/ranking/s8-2026-barcelona-hyrox-women",
        "total_atletas": 1296
    }
}

## 4. HYROX Men Barcelona 2026

### 4.1 Ranking hombres

In [7]:
ruta_ranking_men = f"{RUTA_DATOS}/barcelona2026_hyrox_men_ranking.csv"

if os.path.exists(ruta_ranking_men):
    print("Cargando ranking masculino desde Drive")
    df_men = pd.read_csv(ruta_ranking_men)
else:
    print("Descargando ranking masculino")
    df_men = descargar_categoria_completa(
        ranking_url=categorias["men"]["ranking_url"],
        total_atletas=categorias["men"]["total_atletas"],
        pausa=0.5
    )
    df_men.to_csv(ruta_ranking_men, index=False)

print(df_men.shape)
df_men.head()

Descargando ranking masculino
Descargando página 1/24
Descargando página 2/24
Descargando página 3/24
Descargando página 4/24
Descargando página 5/24
Descargando página 6/24
Descargando página 7/24
Descargando página 8/24
Descargando página 9/24
Descargando página 10/24
Descargando página 11/24
Descargando página 12/24
Descargando página 13/24
Descargando página 14/24
Descargando página 15/24
Descargando página 16/24
Descargando página 17/24
Descargando página 18/24
Descargando página 19/24
Descargando página 20/24
Descargando página 21/24
Descargando página 22/24
Descargando página 23/24
Descargando página 24/24
(2349, 8)

,posicion,posicion_grupo_edad,nombre,pais,grupo_edad,tiempo,athlete_url,analyze_url
0,1,1,Gaetan Gianni,France,16-24,53:44,https://www.hyresult.com/athlete/gaetan-gianni,https://www.hyresult.com/result/LR3MS4JI502C48
1,2,1,Emilio Aguayo,Spain,35-39,56:38,https://www.hyresult.com/athlete/emilio-aguayo,https://www.hyresult.com/result/LR3MS4JI501875
2,3,1,Loic Cebelieu,France,25-29,57:17,https://www.hyresult.com/athlete/loic-cebelieu,https://www.hyresult.com/result/LR3MS4JI5010E6
3,4,1,Ferran Bochaca Sabarich,Spain,30-34,57:24,https://www.hyresult.com/athlete/ferran-bochac...,https://www.hyresult.com/result/LR3MS4JI501D84
4,5,2,Alberto Casado Aroca,Spain,30-34,57:38,https://www.hyresult.com/athlete/alberto-casad...,https://www.hyresult.com/result/LR3MS4JI502972

### 4.2 Splits hombres

In [8]:
ruta_splits_men = f"{RUTA_DATOS}/barcelona2026_hyrox_men_splits.csv"
ruta_errores_men = f"{RUTA_DATOS}/barcelona2026_hyrox_men_errores.csv"

if os.path.exists(ruta_splits_men):
    print("Cargando splits masculinos desde Drive")
    df_splits_men = pd.read_csv(ruta_splits_men)

    if os.path.exists(ruta_errores_men):
        df_errores_men = pd.read_csv(ruta_errores_men)
    else:
        df_errores_men = pd.DataFrame()
else:
    print("Descargando splits masculinos")
    df_splits_men, df_errores_men = descargar_splits_categoria(
        df_men,
        pausa=0.5
    )

    df_splits_men.to_csv(ruta_splits_men, index=False)
    df_errores_men.to_csv(ruta_errores_men, index=False)

print(df_splits_men.shape)
print("Errores:", len(df_errores_men))

Descargando splits masculinos
Extrayendo 1/2349: Gaetan Gianni
Extrayendo 2/2349: Emilio Aguayo
Extrayendo 3/2349: Loic Cebelieu
Extrayendo 4/2349: Ferran Bochaca Sabarich
Extrayendo 5/2349: Alberto Casado Aroca
Extrayendo 6/2349: Sebastien Rajkowski
Extrayendo 7/2349: Mehdi Berrouigat
Extrayendo 8/2349: Pau Nacenta Merinas
Extrayendo 9/2349: Aaron Timmerman
Extrayendo 10/2349: Walter Paladina
Extrayendo 11/2349: Ethan Smith
Extrayendo 12/2349: Mohamed Yassin Kattar
Extrayendo 13/2349: Yoel Ferrer
Extrayendo 14/2349: Russell Christie
Extrayendo 15/2349: Martin Casse
Extrayendo 16/2349: James Francis
Extrayendo 17/2349: Thomas Jurado
Extrayendo 18/2349: Robert Stols
Extrayendo 19/2349: Sam Booth
Extrayendo 20/2349: David San Miguel López
Extrayendo 21/2349: Xabier De Velasco
Extrayendo 22/2349: Javier Puyalto Monaj
Extrayendo 23/2349: Ivan Llorens Catala
Extrayendo 24/2349: Sam Garcia
Extrayendo 25/2349: John Murtagh
Extrayendo 26/2349: Julien Caujolle
Extrayendo 27/2349: Luis Caja Nacher
Extrayendo 28/2349: Joost Huisink
Extrayendo 29/2349: Yann Borderie
Extrayendo 30/2349: Rodrigo de Zatarain Llaca
Extrayendo 31/2349: Alex Lang
Extrayendo 32/2349: Pepe Juangran
Extrayendo 33/2349: Jordan Lynch
Extrayendo 34/2349: Étienne Lite
Extrayendo 35/2349: Gonzalo Espejo Del Rio
Extrayendo 36/2349: Axel Solegre
Extrayendo 37/2349: Alessandro Rossi
Extrayendo 38/2349: Maxime Bonelli
Extrayendo 39/2349: Ignacio Dañobeitia
Extrayendo 40/2349: Richard Daniels
Extrayendo 41/2349: Rubén García Carnicero
Extrayendo 42/2349: Tomaž Gojčič
Extrayendo 43/2349: Ansumana Konteh Sanneh
Extrayendo 44/2349: Ian Michalik
Extrayendo 45/2349: Marc Sadurni De La Torre
Extrayendo 46/2349: Marcos Caballero Corral
Extrayendo 47/2349: Theodore Golan
Extrayendo 48/2349: Mikek Salgado Imaz
Extrayendo 49/2349: Colin Davy
Extrayendo 50/2349: Barney Fairnington
Extrayendo 51/2349: Alvaro Monedero
Extrayendo 52/2349: Teun Alberts
Extrayendo 53/2349: Jules Chouvin
Extrayendo 54/2349: Matthieu Vanbaelinghem
Extrayendo 55/2349: Will Wellon
Extrayendo 56/2349: Aaron Cleaver
Extrayendo 57/2349: Jordan Noble
Extrayendo 58/2349: José Ramón Rodes Martinez
Extrayendo 59/2349: Ioannis Marinou
Extrayendo 60/2349: Steven Broxton
Extrayendo 61/2349: Manu Lacaba
Extrayendo 62/2349: Piripi Korent
Extrayendo 63/2349: Dylan Hobson
Extrayendo 64/2349: Sjors Lankhaar
Extrayendo 65/2349: Thomas Lorblanchet
Extrayendo 66/2349: Maxime Bordeaux
Extrayendo 67/2349: Corentin Loiseaux
Extrayendo 68/2349: Driss Alami
Extrayendo 69/2349: David Damjakob
Extrayendo 70/2349: Gerard Pericay Freixes
Extrayendo 71/2349: Thomas Capitani
Extrayendo 72/2349: Loris Thomas
Extrayendo 73/2349: Tom France
Extrayendo 74/2349: Sergi Garcia Magrans
Extrayendo 75/2349: Lewys Mccafferty
Extrayendo 76/2349: Matthieu Andujar
Extrayendo 77/2349: Pierrick Chaume
Extrayendo 78/2349: Mickael Braye
Extrayendo 79/2349: Kevin Horner
Extrayendo 80/2349: Lucas Parron Barcelona
Extrayendo 81/2349: Igor Rojo
Extrayendo 82/2349: Cormac Hannan
Extrayendo 83/2349: Juan Pajares
Extrayendo 84/2349: Marc Houngbedji
Extrayendo 85/2349: Robert Sobczak
Extrayendo 86/2349: Anthony Mendes
Extrayendo 87/2349: Paul Marleux
Extrayendo 88/2349: Ivan De Mora Martín
Extrayendo 89/2349: Eoghan O Murchu
Extrayendo 90/2349: Bernardo Neto
Extrayendo 91/2349: Alvaro Cardona
Extrayendo 92/2349: Clément Rojas
Extrayendo 93/2349: Alex Rowlands
Extrayendo 94/2349: Adham Hany
Extrayendo 95/2349: Mackenzie Heaney
Extrayendo 96/2349: Romain Marais
Extrayendo 97/2349: NICOLAS ALBERTO HERNANDEZ SANCHEZ
Extrayendo 98/2349: Luke Wise
Extrayendo 99/2349: Pierluigi Senor
Extrayendo 100/2349: Marceau Crayssac
Extrayendo 101/2349: Temoe Fels
Extrayendo 102/2349: Maxime Renard
Extrayendo 103/2349: Nils Lombard
Extrayendo 104/2349: Javier Carmona  Mansilla
Extrayendo 105/2349: Alejandro Vera Blanco
Extrayendo 106/2349: Nahuel Galván
Extrayendo 107/2349: Marc Guillazo
Extrayendo 108/2349: Nicolas LITCHMAN
Extrayendo 109/2349: Felix Casalod
Extrayendo 110/2349: Richard Gill
Extrayendo 111/2349: Victor Peña
Extrayendo 112/2349: Bastien Nugon
Extrayendo 113/2349: Sebastian Fernández Espinoza De Los Mont
Extrayendo 114/2349: Ben Parry
Extrayendo 115/2349: Paraic Hannan
Extrayendo 116/2349: Kaveh Farahmand
Extrayendo 117/2349: Guillaume Chusseau
Extrayendo 118/2349: Nicolas Darrieutort
Extrayendo 119/2349: Juan Antonio Arenas
Extrayendo 120/2349: Bixente Orance
Extrayendo 121/2349: Daniel Johnson
Extrayendo 122/2349: Santi Valle
Extrayendo 123/2349: Tiler Jones
Extrayendo 124/2349: Ben Whittaker
Extrayendo 125/2349: Diogo Rodrigues
Extrayendo 126/2349: Jonathan Escribano Arjona
Extrayendo 127/2349: Jonathan Eames
Extrayendo 128/2349: Peter Zuravlev
Extrayendo 129/2349: Davide Marone
Extrayendo 130/2349: Guillaume Jolly
Extrayendo 131/2349: Nathan Pierre
Extrayendo 132/2349: Janis Burkhart
Extrayendo 133/2349: Yvan Cina
Extrayendo 134/2349: Rafa Morgado
Extrayendo 135/2349: Harvey Jones
Extrayendo 136/2349: Rob Amor
Extrayendo 137/2349: Owen Mccue
Extrayendo 138/2349: Alex Iloie
Extrayendo 139/2349: David Delgado
Extrayendo 140/2349: Jorge Bartolomé Rodríguez
Extrayendo 141/2349: Oscar Cerezuela
Extrayendo 142/2349: Paul Wolf
Extrayendo 143/2349: James Lang
Extrayendo 144/2349: Vincent Ferré
Extrayendo 145/2349: Ahmed Alhashmi
Extrayendo 146/2349: Heros Iapello
Extrayendo 147/2349: Morgan O Donoghue
Extrayendo 148/2349: Eoghan Daly
Extrayendo 149/2349: Harry Behrens
Extrayendo 150/2349: Fernando Pajares
Extrayendo 151/2349: Cyril Benech
Extrayendo 152/2349: Marcos Palomero
Extrayendo 153/2349: Teo Arasa Cid
Extrayendo 154/2349: Joshua Drake
Extrayendo 155/2349: Ross Mcgarry
Extrayendo 156/2349: João Matos
Extrayendo 157/2349: Ralph Walker-Moretti
Extrayendo 158/2349: Miguel Franco Ruas
Extrayendo 159/2349: Alexandre Viala
Extrayendo 160/2349: Aaron Cullen
Extrayendo 161/2349: Tom Woods
Extrayendo 162/2349: Matthias Duelund Pedersen
Extrayendo 163/2349: Enric Costa Torrents
Extrayendo 164/2349: Thibault Boullé
Extrayendo 165/2349: Adrián Bonilla
Extrayendo 166/2349: Guillem Sanchis
Extrayendo 167/2349: Feliu Coronado
Extrayendo 168/2349: Paul Cérantola
Extrayendo 169/2349: Jack Forrester
Extrayendo 170/2349: Iñaki Gonzalez Veintemillas
Extrayendo 171/2349: Arturo Oliva
Extrayendo 172/2349: Roberto Reina
Extrayendo 173/2349: Théo Valero
Extrayendo 174/2349: Pablo Moraga
Extrayendo 175/2349: Ausaine Konteh Sanneh
Extrayendo 176/2349: Toni Horcajada Lopez
Extrayendo 177/2349: Alex Rodiera
Extrayendo 178/2349: Simon Raeyen
Extrayendo 179/2349: Carlos Pajares
Extrayendo 180/2349: Haritz Blanco Bello
Extrayendo 181/2349: Matt Burford
Extrayendo 182/2349: Claret Rosset
Extrayendo 183/2349: Pablo Calvo Iborra
Extrayendo 184/2349: Teddy Mallet
Extrayendo 185/2349: Zackary Gueddari
Extrayendo 186/2349: Jiří Skácelík
Extrayendo 187/2349: Szymon Mochnacz
Extrayendo 188/2349: Ladjie Niakate
Extrayendo 189/2349: Alejandro Morón Castillo
Extrayendo 190/2349: Arno Herssens
Extrayendo 191/2349: Nathaniel Morris
Extrayendo 192/2349: RUI PEDRO SILVA
Extrayendo 193/2349: Mohammad Jafar
Extrayendo 194/2349: Evan Collumbine
Extrayendo 195/2349: Jonathan Delbert
Extrayendo 196/2349: Victor Peña Gomez
Extrayendo 197/2349: Christopher Harger
Extrayendo 198/2349: Dawid Andrzej Mwila
Extrayendo 199/2349: Jose Martinez
Extrayendo 200/2349: James Pyne
Extrayendo 201/2349: Ramón Gutiérrez Sánchez
Extrayendo 202/2349: Ruben Oliveira
Extrayendo 203/2349: William Matthews
Extrayendo 204/2349: Nathan Condon
Extrayendo 205/2349: Edoardo Nodaro
Extrayendo 206/2349: Jérémie Guenole
Extrayendo 207/2349: Gorka Sanchez
Extrayendo 208/2349: Oscar Valentin Garcia
Extrayendo 209/2349: Joshua Scott
Extrayendo 210/2349: Tom Stewart
Extrayendo 211/2349: Jose Miguel Lopez Sanchez
Extrayendo 212/2349: Julien Ponti
Extrayendo 213/2349: Marvin Patras
Extrayendo 214/2349: Javier Russo
Extrayendo 215/2349: Ivan Lanceta
Extrayendo 216/2349: Lucas Ait Benamara
Extrayendo 217/2349: Diony Torrero
Extrayendo 218/2349: Dan Thomas
Extrayendo 219/2349: Alban Soulié
Extrayendo 220/2349: Ivan Bailach
Extrayendo 221/2349: Eric Infante Garcia
Extrayendo 222/2349: André Agostinho
Extrayendo 223/2349: Mette Stam
Extrayendo 224/2349: Nicolas Boissy
Extrayendo 225/2349: Unai Cruz
Extrayendo 226/2349: Bruno Ramos
Extrayendo 227/2349: Nicolas Landes
Extrayendo 228/2349: Marc Domenjó
Extrayendo 229/2349: Charly Bertrand
Extrayendo 230/2349: Micael Vieira
Extrayendo 231/2349: James Cahalane
Extrayendo 232/2349: Austyn Hardy
Extrayendo 233/2349: Aleix Felip
Extrayendo 234/2349: Lorin Martinez
Extrayendo 235/2349: Nico Plück
Extrayendo 236/2349: Edgar Sundt
Extrayendo 237/2349: Juan Julián Morcillo González
Extrayendo 238/2349: Roger Farré
Extrayendo 239/2349: Darren Williscroft
Extrayendo 240/2349: Jack Redfern
Extrayendo 241/2349: Fabio Lorenzon
Extrayendo 242/2349: Josh Carrigan
Extrayendo 243/2349: Robin Deslandes
Extrayendo 244/2349: Jean-Baptiste Grimal
Extrayendo 245/2349: Robbie Clyne
Extrayendo 246/2349: Vincent Gibert
Extrayendo 247/2349: Sascha Rohner
Extrayendo 248/2349: Biagio Rubinaccio
Extrayendo 249/2349: Josu Gilen Hualde
Extrayendo 250/2349: Rémi Pauly
Extrayendo 251/2349: Pablo Gomis De Gabriel
Extrayendo 252/2349: Matt Griffiths
Extrayendo 253/2349: Kevin Walter
Extrayendo 254/2349: Alejandro Esteban Loza
Extrayendo 255/2349: Cristian Costa
Extrayendo 256/2349: Sergi Saez
Extrayendo 257/2349: Olivier Beugin
Extrayendo 258/2349: Pau Aguiló  Mayol
Extrayendo 259/2349: Mathias Maxa
Extrayendo 260/2349: Jordan Auvergne
Extrayendo 261/2349: Remco Waanders
Extrayendo 262/2349: Nicolas Coppet
Extrayendo 263/2349: James Russell
Extrayendo 264/2349: Rui Leite
Extrayendo 265/2349: Ross Walker
Extrayendo 266/2349: Henry Hodge
Extrayendo 267/2349: Cedric Puaud
Extrayendo 268/2349: Zach Calnan
Extrayendo 269/2349: Craig Douglas
Extrayendo 270/2349: Adrian Enright
Extrayendo 271/2349: Alex Parmentier
Extrayendo 272/2349: Andrew Shields
Extrayendo 273/2349: Antonio Illan Garcia
Extrayendo 274/2349: Tomás Leal
Extrayendo 275/2349: Benjamin Martinez
Extrayendo 276/2349: Sergi Rubio
Extrayendo 277/2349: Tanguy Martin
Extrayendo 278/2349: Bastien Etcheverria
Extrayendo 279/2349: Eric Sendas
Extrayendo 280/2349: Enrico Ticoalu
Extrayendo 281/2349: Karol Kutta
Extrayendo 282/2349: Tera Tapao
Extrayendo 283/2349: Josh Harper
Extrayendo 284/2349: Mauro Grioli
Extrayendo 285/2349: Lorenzo Resta
Extrayendo 286/2349: Mario Dieste Ballarin
Extrayendo 287/2349: Ellis Wiffen
Extrayendo 288/2349: Fernando Arias
Extrayendo 289/2349: Guillermo Fernandez Moraleda
Extrayendo 290/2349: Daniele Cotti
Extrayendo 291/2349: Jose Antonio Martin Quiroga
Extrayendo 292/2349: Anthony Laborde
Extrayendo 293/2349: Sergio Turull
Extrayendo 294/2349: Willem Ballet
Extrayendo 295/2349: Maxime Larramendy
Extrayendo 296/2349: Benjamin Bruns
Extrayendo 297/2349: David Saus
Extrayendo 298/2349: Manuel Valtulini
Extrayendo 299/2349: Max Myers
Extrayendo 300/2349: Aurelien Gedon
Extrayendo 301/2349: Matt Kelly
Extrayendo 302/2349: Obiora Onuora
Extrayendo 303/2349: Samson Brown
Extrayendo 304/2349: Theo Ferin
Extrayendo 305/2349: Jesús Guillén
Extrayendo 306/2349: Jack Rea
Extrayendo 307/2349: Tristan Le Moing
Extrayendo 308/2349: Christian Göller
Extrayendo 309/2349: Timm Ehret
Extrayendo 310/2349: Darren Morgan
Extrayendo 311/2349: Roger Cayuela
Extrayendo 312/2349: Omar Eissa
Extrayendo 313/2349: Juan Gómez Miralles
Extrayendo 314/2349: Emmanuel Quemerais
Extrayendo 315/2349: Rowen Koot
Extrayendo 316/2349: Mickael Guignard
Extrayendo 317/2349: Ewen Cheval
Extrayendo 318/2349: Fabian Althammer
Extrayendo 319/2349: Carlos Ruiz Manuel
Extrayendo 320/2349: Yoan Gomez
Extrayendo 321/2349: Davide Nappo
Extrayendo 322/2349: Philipp Ströming
Extrayendo 323/2349: Callum Keavey
Extrayendo 324/2349: Lluis Pons Pons
Extrayendo 325/2349: David Fernández
Extrayendo 326/2349: Niall Clinton
Extrayendo 327/2349: Faustas Stoncius
Extrayendo 328/2349: Richard Burrows
Extrayendo 329/2349: Sam Armand
Extrayendo 330/2349: Ruben Torrado Nogales
Extrayendo 331/2349: Evan Morvan
Extrayendo 332/2349: Steven Copeland
Extrayendo 333/2349: Gabriel Fleury
Extrayendo 334/2349: Francesco Borsari
Extrayendo 335/2349: Daniel Knox
Extrayendo 336/2349: Martin Hoffmann
Extrayendo 337/2349: Mariano Ramis
Extrayendo 338/2349: Dominykas Jutas
Extrayendo 339/2349: Jordi Bonet Domínguez
Extrayendo 340/2349: Isaac Backhouse
Extrayendo 341/2349: Maximilian Delakowitz
Extrayendo 342/2349: Jason Albon
Extrayendo 343/2349: Ed Miles
Extrayendo 344/2349: Jesus Aguado Agenjo
Extrayendo 345/2349: Tiago Cristo
Extrayendo 346/2349: Justyn Mckay
Extrayendo 347/2349: Sandro Hörler
Extrayendo 348/2349: Marco Grübl
Extrayendo 349/2349: Jesus Baquedano Mozos
Extrayendo 350/2349: Toni Gilart
Extrayendo 351/2349: Sébastien Garro
Extrayendo 352/2349: Loic Gironde
Extrayendo 353/2349: Luis Maggio
Extrayendo 354/2349: Ricardo Goizueta
Extrayendo 355/2349: Matthew Moslenko
Extrayendo 356/2349: Álvaro Crespo Maeztu
Extrayendo 357/2349: Meinhard Meintjes
Extrayendo 358/2349: Jonathan Cody
Extrayendo 359/2349: Lloyd Echegaray Frances
Extrayendo 360/2349: Kevin Nino
Extrayendo 361/2349: Nate B
Extrayendo 362/2349: Marc Gunter
Extrayendo 363/2349: Mateus Saraiva
Extrayendo 364/2349: Hugo Barros Alonso
Extrayendo 365/2349: Frédérick Fisson
Extrayendo 366/2349: Aaron Zahra
Extrayendo 367/2349: Armando Silva
Extrayendo 368/2349: Ruben Beltran
Extrayendo 369/2349: Pablo Fernandez Cañete
Extrayendo 370/2349: Aurélien Artinian
Extrayendo 371/2349: Thomas Arcas
Extrayendo 372/2349: Aidan Hyland
Extrayendo 373/2349: Alexis Emanuel Olivares
Extrayendo 374/2349: Alexandre Kong
Extrayendo 375/2349: Jacob Gratton
Extrayendo 376/2349: Cyril Puech
Extrayendo 377/2349: Álvaro Torres
Extrayendo 378/2349: Simao Saraiva
Extrayendo 379/2349: Florent Besombes
Extrayendo 380/2349: Joey Van De Kerkhof
Extrayendo 381/2349: Andy Br
Extrayendo 382/2349: Marc Ollé
Extrayendo 383/2349: Joel Perez Valencia
Extrayendo 384/2349: Guillaume Clert
Extrayendo 385/2349: Jack Scully
Extrayendo 386/2349: Ivan Serrano
Extrayendo 387/2349: Kylane Ait Hamou
Extrayendo 388/2349: Borja Sepulveda
Extrayendo 389/2349: Fernando Gurrea
Extrayendo 390/2349: Alessandro Benedetti
Extrayendo 391/2349: Joan Carles Castella
Extrayendo 392/2349: Kevin Labaume
Extrayendo 393/2349: Sascha Dewald
Extrayendo 394/2349: David Gomtsyan
Extrayendo 395/2349: Glen Preibisch Lecha
Extrayendo 396/2349: Mathias Saal
Extrayendo 397/2349: Guillem Rives
Extrayendo 398/2349: Phil Schwarick
Extrayendo 399/2349: Christian Saylor
Extrayendo 400/2349: Gaëtan Lopez
Extrayendo 401/2349: Luca Delgrosso
Extrayendo 402/2349: Max Smith
Extrayendo 403/2349: Troy Rouse
Extrayendo 404/2349: Mehdi Sabiri
Extrayendo 405/2349: Manyacca Menyoli
Extrayendo 406/2349: Marcos Aguilar Finez
Extrayendo 407/2349: Cédric Mazenq
Extrayendo 408/2349: Adrián Tello Beneit
Extrayendo 409/2349: Mickael Pascual
Extrayendo 410/2349: Clement Sarrat
Extrayendo 411/2349: Rob Worthington
Extrayendo 412/2349: Dan Addis
Extrayendo 413/2349: Théophile Deffrennes
Extrayendo 414/2349: Angel Pinilla Ciria
Extrayendo 415/2349: Eduardo Sánchez
Extrayendo 416/2349: Robert Baczewski
Extrayendo 417/2349: Christopher Roseau
Extrayendo 418/2349: Jens Weipert
Extrayendo 419/2349: Mathieu Peyris
Extrayendo 420/2349: António Piçarra
Extrayendo 421/2349: Jahmal Howlett-Mundle
Extrayendo 422/2349: Manuel Rizzetto
Extrayendo 423/2349: Johan Billoud
Extrayendo 424/2349: Hector Diaz
Extrayendo 425/2349: Ángel Fernández
Extrayendo 426/2349: Florian Preiss
Extrayendo 427/2349: John Hallopé
Extrayendo 428/2349: Jonny Sasati
Extrayendo 429/2349: Sebastian Harris
Extrayendo 430/2349: Pablo Anitua Diez
Extrayendo 431/2349: Karl Yelland
Extrayendo 432/2349: Rubén David Del Pino Serrano
Extrayendo 433/2349: Fernando Tena
Extrayendo 434/2349: Jamie Randall
Extrayendo 435/2349: James Bidwell
Extrayendo 436/2349: Niall Goodwin
Extrayendo 437/2349: Roy Céansu
Extrayendo 438/2349: Liam Mcclure
Extrayendo 439/2349: Tom Starling
Extrayendo 440/2349: Sam Draper
Extrayendo 441/2349: Jeremy Outmanns
Extrayendo 442/2349: Angel De Las Heras Lopez
Extrayendo 443/2349: Edward Whelan
Extrayendo 444/2349: Nicholas Abbott
Extrayendo 445/2349: Ilja Feilinger
Extrayendo 446/2349: Alan Cusack
Extrayendo 447/2349: Antoine Aldebert
Extrayendo 448/2349: Niclas Blåklinth
Extrayendo 449/2349: Guido Viggiani
Extrayendo 450/2349: Amadeo Villar Guardia
Extrayendo 451/2349: Sönke Weber
Extrayendo 452/2349: Ugo Porta
Extrayendo 453/2349: Veit Florian Kopenec
Extrayendo 454/2349: Bo Evertse
Extrayendo 455/2349: Javi Penadés
Extrayendo 456/2349: Julien Affre
Extrayendo 457/2349: Tom Darneix
Extrayendo 458/2349: Mikel Tamayo
Extrayendo 459/2349: Dan Harding
Extrayendo 460/2349: Luis Moyano Fernandez
Extrayendo 461/2349: Jaromír Täuber
Extrayendo 462/2349: Ignacio Mazon
Extrayendo 463/2349: Joris Harink
Extrayendo 464/2349: Reece Jefferson
Extrayendo 465/2349: Imad Chakor Djelthia
Extrayendo 466/2349: Liam White
Extrayendo 467/2349: Mickael Benyamina
Extrayendo 468/2349: Christian Perini
Extrayendo 469/2349: Enric Arbós Reyes
Extrayendo 470/2349: Sam Morley
Extrayendo 471/2349: Kevin Mansuy
Extrayendo 472/2349: Mateusz Zwierz
Extrayendo 473/2349: Stephen Maher
Extrayendo 474/2349: Anton Kostenzer
Extrayendo 475/2349: Marlon Duque
Extrayendo 476/2349: Federico Tonin
Extrayendo 477/2349: Julien Richalet
Extrayendo 478/2349: Patxi Mikel Triguero
Extrayendo 479/2349: Guillaume Cado
Extrayendo 480/2349: Nathan Poulet
Extrayendo 481/2349: Yoann Le Guen
Extrayendo 482/2349: Joshua Dams
Extrayendo 483/2349: Pablo Romero
Extrayendo 484/2349: mickael cavailles
Extrayendo 485/2349: Jo Curutchague
Extrayendo 486/2349: Kyle O'Donoghue
Extrayendo 487/2349: Joshua Moss
Extrayendo 488/2349: Stig René Bersaas Oldervik
Extrayendo 489/2349: Callum Tusler
Extrayendo 490/2349: Marco Vitoria Fagnani
Extrayendo 491/2349: David Hermo Blanco
Extrayendo 492/2349: Sergi Ayala
Extrayendo 493/2349: Mathias Bonis
Extrayendo 494/2349: Diego Zamorano Villar
Extrayendo 495/2349: Vincent Guillard
Extrayendo 496/2349: Aleksandar Stanev
Extrayendo 497/2349: Alvaro Vicente
Extrayendo 498/2349: Antonio Sanchez Gea
Extrayendo 499/2349: Antonio Casas
Extrayendo 500/2349: Luke Page
Extrayendo 501/2349: Simon Phillips
Extrayendo 502/2349: Sean Haughey
Extrayendo 503/2349: Simone Enrici
Extrayendo 504/2349: Charles Arsendaux
Extrayendo 505/2349: Nicolas Berruet
Extrayendo 506/2349: Stephane Pereira
Extrayendo 507/2349: Zach Shellman
Extrayendo 508/2349: Ricardo Martinez
Extrayendo 509/2349: Hugo Richomme
Extrayendo 510/2349: Paweł Studniarek
Extrayendo 511/2349: Oscar Aguilar Illana
Extrayendo 512/2349: Pedro Gonçalves
Extrayendo 513/2349: Ángel Caravaca Huertas
Extrayendo 514/2349: Amir Shkodra
Extrayendo 515/2349: Samuel Osmond
Extrayendo 516/2349: Matheo Gouley
Extrayendo 517/2349: Javier Altable
Extrayendo 518/2349: Rémi Jaunet
Extrayendo 519/2349: Lukas Kaspar
Extrayendo 520/2349: Samuel O'Sullivan
Extrayendo 521/2349: András Obsuszt
Extrayendo 522/2349: Gaetan Grau
Extrayendo 523/2349: Petros Kalodimos
Extrayendo 524/2349: Valentin Dorbes
Extrayendo 525/2349: Niklas Schurig
Extrayendo 526/2349: Manuel Oton Gallardo
Extrayendo 527/2349: Domingo Aguilera
Extrayendo 528/2349: Sergiu Olteanu
Extrayendo 529/2349: Nicolas Lespiauc
Extrayendo 530/2349: Enzo Perez
Extrayendo 531/2349: Samuele Monari
Extrayendo 532/2349: Jesse Van Krimpen
Extrayendo 533/2349: Ricardo Pillay
Extrayendo 534/2349: Miguel Hernandez
Extrayendo 535/2349: Nestor Atienza
Extrayendo 536/2349: Nik Vrešnjak
Extrayendo 537/2349: Erwan Daniel
Extrayendo 538/2349: Daniel Martin Ridruejo
Extrayendo 539/2349: Patrick Moloney
Extrayendo 540/2349: Kris Burns
Extrayendo 541/2349: Adrian Ojeda Almenar
Extrayendo 542/2349: Matis Cabrita
Extrayendo 543/2349: Przemysław Kopeć
Extrayendo 544/2349: Marc Chappelle
Extrayendo 545/2349: Nathan Hawkins
Extrayendo 546/2349: Darío Olivares
Extrayendo 547/2349: Luca Fiorani
Extrayendo 548/2349: Eric Harmsen

## 5. HYROX Women Barcelona 2026

### 5.1 Ranking mujeres

In [9]:
ruta_ranking_women = f"{RUTA_DATOS}/barcelona2026_hyrox_women_ranking.csv"

if os.path.exists(ruta_ranking_women):
    print("Cargando ranking femenino desde Drive")
    df_women = pd.read_csv(ruta_ranking_women)
else:
    print("Descargando ranking femenino")
    df_women = descargar_categoria_completa(
        ranking_url=categorias["women"]["ranking_url"],
        total_atletas=categorias["women"]["total_atletas"],
        pausa=0.5
    )
    df_women.to_csv(ruta_ranking_women, index=False)

print(df_women.shape)
df_women.head()

Descargando ranking femenino
Descargando página 1/13
Descargando página 2/13
Descargando página 3/13
Descargando página 4/13
Descargando página 5/13
Descargando página 6/13
Descargando página 7/13
Descargando página 8/13
Descargando página 9/13
Descargando página 10/13
Descargando página 11/13
Descargando página 12/13
Descargando página 13/13
(1296, 8)

,posicion,posicion_grupo_edad,nombre,pais,grupo_edad,tiempo,athlete_url,analyze_url
0,1,1,Marta Izquierdo Ayuso,Spain,25-29,1:03:59,https://www.hyresult.com/athlete/marta-izquier...,https://www.hyresult.com/result/LR3MS4JI502F6D
1,2,1,Julia Ernst,Germany,30-34,1:05:03,https://www.hyresult.com/athlete/julia-ernst,https://www.hyresult.com/result/LR3MS4JI5026B5
2,3,2,Michela Borzoni,United Kingdom,30-34,1:05:57,https://www.hyresult.com/athlete/michela-borzoni,https://www.hyresult.com/result/LR3MS4JI503921
3,4,3,Lisa Gillman,Ireland,30-34,1:06:23,https://www.hyresult.com/athlete/lisa-gillman,https://www.hyresult.com/result/LR3MS4JI501390
4,5,1,Cristina Villarreal,Mexico,16-24,1:07:03,https://www.hyresult.com/athlete/cristina-vill...,https://www.hyresult.com/result/LR3MS4JI5010C1

### 5.2 Splits Mujeres

In [10]:
ruta_splits_women = f"{RUTA_DATOS}/barcelona2026_hyrox_women_splits.csv"
ruta_errores_women = f"{RUTA_DATOS}/barcelona2026_hyrox_women_errores.csv"

if os.path.exists(ruta_splits_women):
    print("Cargando splits femeninos desde Drive")
    df_splits_women = pd.read_csv(ruta_splits_women)

    if os.path.exists(ruta_errores_women):
        df_errores_women = pd.read_csv(ruta_errores_women)
    else:
        df_errores_women = pd.DataFrame()
else:
    print("Descargando splits femeninos")
    df_splits_women, df_errores_women = descargar_splits_categoria(
        df_women,
        pausa=0.5
    )

    df_splits_women.to_csv(ruta_splits_women, index=False)
    df_errores_women.to_csv(ruta_errores_women, index=False)

print(df_splits_women.shape)
print("Errores:", len(df_errores_women))

Descargando splits femeninos
Extrayendo 1/1296: Marta Izquierdo Ayuso
Extrayendo 2/1296: Julia Ernst
Extrayendo 3/1296: Michela Borzoni
Extrayendo 4/1296: Lisa Gillman
Extrayendo 5/1296: Cristina Villarreal
Extrayendo 6/1296: Erin Ireland
Extrayendo 7/1296: Yessica Pérez Torrente
Extrayendo 8/1296: Laetitia Duhamel
Extrayendo 9/1296: Laura Hawkins
Extrayendo 10/1296: Anna Kirsch
Extrayendo 11/1296: Gracious Phillips
Extrayendo 12/1296: Malen Barceló
Extrayendo 13/1296: Claudia Grau
Extrayendo 14/1296: Valeria Andreini
Extrayendo 15/1296: Maria Fernanda Lopez
Extrayendo 16/1296: Eva Den Uijl
Extrayendo 17/1296: Sophia Öjhammar
Extrayendo 18/1296: Lisa Liberio
Extrayendo 19/1296: ANNA SANTIDRIAN
Extrayendo 20/1296: Britt Gillott
Extrayendo 21/1296: Linda De Wildt
Extrayendo 22/1296: María del Camino del Blanco
Extrayendo 23/1296: Joséphine Segard
Extrayendo 24/1296: Sydnie Schindler
Extrayendo 25/1296: Laura Salvia
Extrayendo 26/1296: Sami Stoute
Extrayendo 27/1296: Catherine Schroeder
Extrayendo 28/1296: Selene Collados Blazquez
Extrayendo 29/1296: Brenda Borgo
Extrayendo 30/1296: Delphine Jalran
Extrayendo 31/1296: Karina Alcala
Extrayendo 32/1296: Giulia Sandrini
Extrayendo 33/1296: Joanne Smith
Extrayendo 34/1296: Maddie Price
Extrayendo 35/1296: Ainoa Vilalta
Extrayendo 36/1296: Bárbara Almeida
Extrayendo 37/1296: Haylie Jones
Extrayendo 38/1296: Naomi Anderson
Extrayendo 39/1296: Ana Hernando
Extrayendo 40/1296: Mar Lozano-Casanova
Extrayendo 41/1296: Berta Medina
Extrayendo 42/1296: Gina Sukmanowski
Extrayendo 43/1296: Tatu Nodari-Blattner
Extrayendo 44/1296: Jacqui Thomson
Extrayendo 45/1296: Alisa Kuznetsova
Extrayendo 46/1296: Marion Geeraedts
Extrayendo 47/1296: Nell Hemansbrook
Extrayendo 48/1296: Flavia Barrera Bazan
Extrayendo 49/1296: Paméla Phillipps
Extrayendo 50/1296: Barbara Zgoda
Extrayendo 51/1296: Esther Arranz Tolos
Extrayendo 52/1296: Claire Bonnet
Extrayendo 53/1296: Chloe Hand
Extrayendo 54/1296: Ana Cecilia Sydow Muñoz-Castillo
Extrayendo 55/1296: Inge Sengers
Extrayendo 56/1296: Jodie Moulding
Extrayendo 57/1296: Lise Madary
Extrayendo 58/1296: Adele Pegram
Extrayendo 59/1296: Gillian Welsh
Extrayendo 60/1296: Amy McNair
Extrayendo 61/1296: Sinead O Reilly
Extrayendo 62/1296: Danielle Giles
Extrayendo 63/1296: Carla Páramo
Extrayendo 64/1296: Sònia Noell Canaleta
Extrayendo 65/1296: Samantha Nevill
Extrayendo 66/1296: Apolline Le Cann
Extrayendo 67/1296: Mia Peters
Extrayendo 68/1296: Louise Bowman
Extrayendo 69/1296: Laura Ortiz Jaén
Extrayendo 70/1296: Grace Alexander
Extrayendo 71/1296: Maialen Sarasua
Extrayendo 72/1296: Florencia Garcia
Extrayendo 73/1296: Sophie Von Der Eltz
Extrayendo 74/1296: Rita Miškinienė
Extrayendo 75/1296: Kirstyn Wylde
Extrayendo 76/1296: Lillian Dramsdahl
Extrayendo 77/1296: Léana Riss
Extrayendo 78/1296: Soraya Croci
Extrayendo 79/1296: Lisa Helluy
Extrayendo 80/1296: Eiran Simmons
Extrayendo 81/1296: Olivia Page
Extrayendo 82/1296: Eva Reboll Rausell
Extrayendo 83/1296: Cristina Calvo
Extrayendo 84/1296: Caroline Pacheco
Extrayendo 85/1296: Morgan Reardon
Extrayendo 86/1296: Rachel Amos
Extrayendo 87/1296: Iraia Amezcua Fernández
Extrayendo 88/1296: Deirdre O Reilly
Extrayendo 89/1296: Jesica Quesada
Extrayendo 90/1296: Brooke Cresswell
Extrayendo 91/1296: Nadine Baumgartner
Extrayendo 92/1296: Elisa Martinez
Extrayendo 93/1296: Hanne Egeberg
Extrayendo 94/1296: Clélia Occhipinti
Extrayendo 95/1296: Noelia Salaverri Mora
Extrayendo 96/1296: Amira Elmisurati
Extrayendo 97/1296: Leah-Mae Weatherhead
Extrayendo 98/1296: Alba Lecumberri
Extrayendo 99/1296: Salma Ghazzawi
Extrayendo 100/1296: Alessia Delogu
Extrayendo 101/1296: Svitlana Holosna
Extrayendo 102/1296: Sara TARRIT
Extrayendo 103/1296: Carolina Ringstmeyer
Extrayendo 104/1296: Ruth Arnold
Extrayendo 105/1296: Lauren Williams
Extrayendo 106/1296: Chantal Vernooij
Extrayendo 107/1296: Jen Grieves
Extrayendo 108/1296: Alice Maria Tortorici
Extrayendo 109/1296: Anna Villanueva Calvet
Extrayendo 110/1296: Nile Uribarrena
Extrayendo 111/1296: Audrey Guettaf
Extrayendo 112/1296: Paulina Vargas
Extrayendo 113/1296: Michèle Hanselmann
Extrayendo 114/1296: Vanesa Pardo
Extrayendo 115/1296: Nina-Larissa Kolb
Extrayendo 116/1296: Tajka Selan
Extrayendo 117/1296: Margot Lecaque
Extrayendo 118/1296: Sara Sanchez Rodriguez
Extrayendo 119/1296: Mary Morrell
Extrayendo 120/1296: Lisa Bauer
Extrayendo 121/1296: Jasmine Black
Extrayendo 122/1296: Minnah Deef
Extrayendo 123/1296: Euge Laya
Extrayendo 124/1296: Johanna Guaman González
Extrayendo 125/1296: Jade Brown
Extrayendo 126/1296: Lucía Noguera Álvarez
Extrayendo 127/1296: Denise Warrelmann
Extrayendo 128/1296: Lidia Valdivieso
Extrayendo 129/1296: Linda Hutchinson
Extrayendo 130/1296: Emma Starling
Extrayendo 131/1296: Laura Werni
Extrayendo 132/1296: Lidia Querol
Extrayendo 133/1296: Carolina De Hostos
Extrayendo 134/1296: Maeva Douabin
Extrayendo 135/1296: Petra Signorelli
Extrayendo 136/1296: Marion Vachey
Extrayendo 137/1296: Petra Oswine Pammer
Extrayendo 138/1296: Emilie Le Faou
Extrayendo 139/1296: Rebecca Millar
Extrayendo 140/1296: Juliette Carrere
Extrayendo 141/1296: Ana Carolina Braudes
Extrayendo 142/1296: Laura Gillespie
Extrayendo 143/1296: Ségolène Charles
Extrayendo 144/1296: Eileen Callahan
Extrayendo 145/1296: Gemma Morera Ransanz
Extrayendo 146/1296: Alice Kavanagh
Extrayendo 147/1296: Simone Waterhouse
Extrayendo 148/1296: Maxence Trognon
Extrayendo 149/1296: Suzaan Fourie
Extrayendo 150/1296: Sarah Zimmerhackl
Extrayendo 151/1296: Amy Bauer
Extrayendo 152/1296: Laura Tomaitė-Svipienė
Extrayendo 153/1296: Alannah Denny
Extrayendo 154/1296: Manuela Balastegui
Extrayendo 155/1296: Carolina Correia
Extrayendo 156/1296: Anna Thomas
Extrayendo 157/1296: Stefanie Nowak
Extrayendo 158/1296: Salina Wiedmann
Extrayendo 159/1296: Taxiarchoula Rallidi
Extrayendo 160/1296: Loanne Baena
Extrayendo 161/1296: Raquel Perez Vendrell
Extrayendo 162/1296: Mercè Llopart Ventura
Extrayendo 163/1296: Metah Santos
Extrayendo 164/1296: Cindy Severin
Extrayendo 165/1296: Monica Grafino
Extrayendo 166/1296: Ramona Crüzer
Extrayendo 167/1296: Stefanie Götze
Extrayendo 168/1296: Yuka Nakazato
Extrayendo 169/1296: Camille Combe
Extrayendo 170/1296: Fabiola Martinez
Extrayendo 171/1296: Klara Zeren
Extrayendo 172/1296: Hannah Hollis
Extrayendo 173/1296: Maria Engelson
Extrayendo 174/1296: Sarah Teton
Extrayendo 175/1296: Antonia Mckenna
Extrayendo 176/1296: Betsy Young
Extrayendo 177/1296: Janine Reichmuth
Extrayendo 178/1296: Marta Campos Campos
Extrayendo 179/1296: Marián Llopis Mira
Extrayendo 180/1296: Fabienne Decourt
Extrayendo 181/1296: Amy-May Bampton
Extrayendo 182/1296: Barbara May
Extrayendo 183/1296: Roser Pons Cursach
Extrayendo 184/1296: Isabel Fernández Flores
Extrayendo 185/1296: Sara Angel
Extrayendo 186/1296: Selin Verger
Extrayendo 187/1296: Mariana Cecilia Patiño Díaz
Extrayendo 188/1296: Delphine Taurines
Extrayendo 189/1296: Joanne Edwards
Extrayendo 190/1296: Annabel Thorburn
Extrayendo 191/1296: Megan Young
Extrayendo 192/1296: Nicole Sterki
Extrayendo 193/1296: Andrea Ródenas Calvo
Extrayendo 194/1296: Josefine Köhlmark
Extrayendo 195/1296: Virginie Marquié
Extrayendo 196/1296: Clotilde Mugner Lavarec
Extrayendo 197/1296: Kirsten Ebeltjes
Extrayendo 198/1296: Amandine Mangin
Extrayendo 199/1296: Carly Butler
Extrayendo 200/1296: Valentina Baccega
Extrayendo 201/1296: Pippa Chamley
Extrayendo 202/1296: Carlota Llorens
Extrayendo 203/1296: Carlota Tomas Bello
Extrayendo 204/1296: Orla Meenehan
Extrayendo 205/1296: Marina Burgos Portabella
Extrayendo 206/1296: Maria Fernanda Hernandez Espinosa
Extrayendo 207/1296: Mariem Kaddouri López
Extrayendo 208/1296: Marina Grasso Caubet
Extrayendo 209/1296: Kim Lowden
Extrayendo 210/1296: Anne Sophie Maillot
Extrayendo 211/1296: Emilie Eggs
Extrayendo 212/1296: Gimena Hormachea
Extrayendo 213/1296: Helen Platel
Extrayendo 214/1296: Maria Puig
Extrayendo 215/1296: Carina Wahlum
Extrayendo 216/1296: Chantal Stols
Extrayendo 217/1296: Claire Turner
Extrayendo 218/1296: Paula Bello Aranda
Extrayendo 219/1296: Elise Rae
Extrayendo 220/1296: Cécilia Martin
Extrayendo 221/1296: Celia Romeu
Extrayendo 222/1296: Andrea Brenes Morales
Extrayendo 223/1296: Anastasija Bonevska
Extrayendo 224/1296: Aoife Kennedy
Extrayendo 225/1296: Federica Polonio
Extrayendo 226/1296: Veronica Cardinetti
Extrayendo 227/1296: Nicole Mcnaughten
Extrayendo 228/1296: Gara Rodríguez González
Extrayendo 229/1296: Harry Robinson
Extrayendo 230/1296: Julia Baxter
Extrayendo 231/1296: Karolayne Nahomi Díaz Veliz
Extrayendo 232/1296: Aurélie Soula
Extrayendo 233/1296: Martina Paccagnella
Extrayendo 234/1296: Natalia Martinez
Extrayendo 235/1296: Bea Richardson
Extrayendo 236/1296: Laia Santamaria
Extrayendo 237/1296: Leonela Lepore
Extrayendo 238/1296: Marta Tornés Tornés
Extrayendo 239/1296: Olga Nadibaidze
Extrayendo 240/1296: Olivia Fraser
Extrayendo 241/1296: Amy Broadhurst
Extrayendo 242/1296: Marta Perez Peña
Extrayendo 243/1296: Marta Wizimirska
Extrayendo 244/1296: Eve Candas
Extrayendo 245/1296: Andrea Marti
Extrayendo 246/1296: Diana Sandoval
Extrayendo 247/1296: Laura Raimann
Extrayendo 248/1296: Edurne Aizpurua Pablo
Extrayendo 249/1296: Romi Dangelo
Extrayendo 250/1296: Marcelle Schaffarczyk
Extrayendo 251/1296: Léa Gayraud
Extrayendo 252/1296: Joana Wild
Extrayendo 253/1296: Olivia Addison
Extrayendo 254/1296: Amanda Cruz Silva
Extrayendo 255/1296: Julia Sylvestri
Extrayendo 256/1296: Rebecca Wilkinson
Extrayendo 257/1296: Viola Schweegmann
Extrayendo 258/1296: Jade Herring
Extrayendo 259/1296: Kay Bojovic
Extrayendo 260/1296: Shauna Brennan
Extrayendo 261/1296: Cecile Bruneau
Extrayendo 262/1296: Verena Ries
Extrayendo 263/1296: Marta Sulis
Extrayendo 264/1296: Rwana Badry
Extrayendo 265/1296: Gemma Mier I Cervantes
Extrayendo 266/1296: Pamela Bodei
Extrayendo 267/1296: Bailey Erica Purcka
Extrayendo 268/1296: Dénia Amon
Extrayendo 269/1296: Josephine Yang
Extrayendo 270/1296: Loana Chauvin
Extrayendo 271/1296: Mélanie Fernández Roque
Extrayendo 272/1296: Julie Falguieres
Extrayendo 273/1296: Vicky Gaitan Acosta
Extrayendo 274/1296: Bernadine Galea
Extrayendo 275/1296: Mamen Muñiz
Extrayendo 276/1296: Sulema Roxana Marin
Extrayendo 277/1296: Noémie Maleville
Extrayendo 278/1296: Louise Doone
Extrayendo 279/1296: Gemma Prat
Extrayendo 280/1296: Julia Campbell
Extrayendo 281/1296: Eleanor Burton
Extrayendo 282/1296: Cathy Rees
Extrayendo 283/1296: Amelie Schröer
Extrayendo 284/1296: Laury Dibbes
Extrayendo 285/1296: Daria Gasienica
Extrayendo 286/1296: Chloe Hadfield
Extrayendo 287/1296: Josie Tremlin
Extrayendo 288/1296: Célia Cesolari
Extrayendo 289/1296: Alicia Parejo
Extrayendo 290/1296: Natalia Moreno
Extrayendo 291/1296: Marion Collet
Extrayendo 292/1296: Jesus Fernandes
Extrayendo 293/1296: Carme Donat Miquel
Extrayendo 294/1296: Stella Deneb Cassader
Extrayendo 295/1296: Lucie Fox-Pegg
Extrayendo 296/1296: Charlotte Wallace
Extrayendo 297/1296: Melanie Gomez
Extrayendo 298/1296: Anne-Lise Lecerf
Extrayendo 299/1296: Zoe Williams
Extrayendo 300/1296: Clara Lefebvre
Extrayendo 301/1296: Jara Orta Chincoa
Extrayendo 302/1296: Laura Liebana Cazalla
Extrayendo 303/1296: Lucy Dodds
Extrayendo 304/1296: Alissa Hasenstab
Extrayendo 305/1296: Joyce Tollenaar
Extrayendo 306/1296: Julia Börner
Extrayendo 307/1296: Fatma Ben Othmen
Extrayendo 308/1296: Emőke Hettyei
Extrayendo 309/1296: Vivien Abraham
Extrayendo 310/1296: Elisabeth Fuss
Extrayendo 311/1296: Séverine Gibert
Extrayendo 312/1296: Ioana Martin
Extrayendo 313/1296: Courtney Blair
Extrayendo 314/1296: Sarah Mifsud
Extrayendo 315/1296: Maria Meyer
Extrayendo 316/1296: Carien Tebbens
Extrayendo 317/1296: Doris Lombardi
Extrayendo 318/1296: Laura O'Donoghue
Extrayendo 319/1296: Ciara Murtagh
Extrayendo 320/1296: Amélie Marchand
Extrayendo 321/1296: Pınar Kul
Extrayendo 322/1296: Ilja Daane
Extrayendo 323/1296: Vendula Hanusová
Extrayendo 324/1296: Paule Lopez
Extrayendo 325/1296: Jaqueline Kabuth
Extrayendo 326/1296: Leanne Quinn
Extrayendo 327/1296: Sophia Dogan
Extrayendo 328/1296: Amira Bayoumy
Extrayendo 329/1296: Josepha Damoiseau
Extrayendo 330/1296: Daniela Diaz Ramos
Extrayendo 331/1296: Andrea Otero Garcia
Extrayendo 332/1296: Samantha Brown
Extrayendo 333/1296: Anna Marie Kala
Extrayendo 334/1296: Sandra Palancar Boluda
Extrayendo 335/1296: Léa Hermant
Extrayendo 336/1296: Katy Gartland
Extrayendo 337/1296: Britta Köhler
Extrayendo 338/1296: Tatiana Andraskova
Extrayendo 339/1296: Carla Martín
Extrayendo 340/1296: Marta Rodríguez Torrado
Extrayendo 341/1296: Rivka Nieuwenhuizen
Extrayendo 342/1296: Sheyla Garcia
Extrayendo 343/1296: Loes Timmermans
Extrayendo 344/1296: Rosie Bexon
Extrayendo 345/1296: Sophie Rattacher
Extrayendo 346/1296: Keiu Pirnpuu
Extrayendo 347/1296: Estela Rojas
Extrayendo 348/1296: Anja Pfeifer
Extrayendo 349/1296: Irina Krasnopolskaia
Extrayendo 350/1296: Shima Adriani
Extrayendo 351/1296: Jeane Lepers
Extrayendo 352/1296: Lara Touza Otero
Extrayendo 353/1296: Laura Charbonnier
Extrayendo 354/1296: Georgia Heupel
Extrayendo 355/1296: Núria Coronado Mur
Extrayendo 356/1296: Ella Butler
Extrayendo 357/1296: Esme Griffiths
Extrayendo 358/1296: Eva Lecoq Joubert
Extrayendo 359/1296: Emiliana Elguezabal
Extrayendo 360/1296: Hayley Mcleod
Extrayendo 361/1296: Valeria Eggers Cortés
Extrayendo 362/1296: Larissa Reintges
Extrayendo 363/1296: Alexa Stein
Extrayendo 364/1296: Heidi Lichtenberg
Extrayendo 365/1296: Claire Samuel
Extrayendo 366/1296: Sarah Pettenati
Extrayendo 367/1296: Barbara Stein
Extrayendo 368/1296: Lucie Guman Bergerova
Extrayendo 369/1296: Maria Jose Belmonte Rodriguez
Extrayendo 370/1296: Annika Berges
Extrayendo 371/1296: Kirsty Lewis-Winrow
Extrayendo 372/1296: Nekane Aparicio
Extrayendo 373/1296: Olivia Rosique
Extrayendo 374/1296: Melissa Krüger
Extrayendo 375/1296: Hannah Byrne
Extrayendo 376/1296: Nicole Fagan
Extrayendo 377/1296: Polina Demanova
Extrayendo 378/1296: Salma Nabli
Extrayendo 379/1296: Evmorfia Chrysovalantou Seiti
Extrayendo 380/1296: Emma Rosen
Extrayendo 381/1296: Regine Werner
Extrayendo 382/1296: Aude Gastauer
Extrayendo 383/1296: Alice Bortoli
Extrayendo 384/1296: Irina Walsh
Extrayendo 385/1296: Charlotte Davies
Extrayendo 386/1296: Courtney Bole
Extrayendo 387/1296: Orkide Guenduez
Extrayendo 388/1296: Claudia Dikkers
Extrayendo 389/1296: Sara Morante
Extrayendo 390/1296: Anastasiia Siniuk
Extrayendo 391/1296: Eleanor Ashton-Melia
Extrayendo 392/1296: Leire Ebrat
Extrayendo 393/1296: Stéphanie Lhuissier
Extrayendo 394/1296: Míriam Solanes
Extrayendo 395/1296: Anais Vatinel
Extrayendo 396/1296: Belen Dominguez
Extrayendo 397/1296: Suzanne Michel
Extrayendo 398/1296: Petra Menhart
Extrayendo 399/1296: Azia To
Extrayendo 400/1296: Ines Pinho
Extrayendo 401/1296: Kelly Defosse
Extrayendo 402/1296: Anna Jürissaar
Extrayendo 403/1296: Justyna Pawełas
Extrayendo 404/1296: Anna Pelegay
Extrayendo 405/1296: Isabelle Amos
Extrayendo 406/1296: Maialen Apoita
Extrayendo 407/1296: Ellie Aston
Extrayendo 408/1296: Nuria Laorga Fernandez
Extrayendo 409/1296: Sara Murga Conde
Extrayendo 410/1296: Mollie Griffith
Extrayendo 411/1296: Claudia Sperber
Extrayendo 412/1296: Selina Kupfer
Extrayendo 413/1296: Annika Gripp
Extrayendo 414/1296: Danielle Diamond
Extrayendo 415/1296: Deborah Filino
Extrayendo 416/1296: Delphine Maffre
Extrayendo 417/1296: Claire-Sophie Cohen
Extrayendo 418/1296: Emma Powell
Extrayendo 419/1296: Anna Calvet
Extrayendo 420/1296: Aruca Siqueira
Extrayendo 421/1296: Marie Jacquenod
Extrayendo 422/1296: Wendy Campbell
Extrayendo 423/1296: Amy Benner
Extrayendo 424/1296: Daniela Lulay
Extrayendo 425/1296: Agathe Robert
Extrayendo 426/1296: Elsa Marguerettaz
Extrayendo 427/1296: Danique Van De Graaf
Extrayendo 428/1296: Tecla Bruto
Extrayendo 429/1296: Katja Košir
Extrayendo 430/1296: Louise Davies
Extrayendo 431/1296: Adriana Fernández
Extrayendo 432/1296: Julia Fuertes Cabello
Extrayendo 433/1296: Marina Arias Martí
Extrayendo 434/1296: Farida Fathy
Extrayendo 435/1296: NAOMI HUGHES
Extrayendo 436/1296: Réka Kubinyi
Extrayendo 437/1296: Elena Maymus
Extrayendo 438/1296: María Díez Manjarrés
Extrayendo 439/1296: Jane Leydon
Extrayendo 440/1296: Mira Wiedemann
Extrayendo 441/1296: Léonie Jammes
Extrayendo 442/1296: Karen Ramirez Bastidas
Extrayendo 443/1296: Ann Emery
Extrayendo 444/1296: Patricia Gohlke
Extrayendo 445/1296: Márcia Souza
Extrayendo 446/1296: Laura Fernandez Alonso
Extrayendo 447/1296: Cristiana Viegas
Extrayendo 448/1296: Shan Zhang
Extrayendo 449/1296: Yesenia Cadavid
Extrayendo 450/1296: Gillian Matthews
Extrayendo 451/1296: Nuria Boné
Extrayendo 452/1296: María José Avila Sandoval
Extrayendo 453/1296: Olga Ortiz Miquel
Extrayendo 454/1296: Abby Wessel
Extrayendo 455/1296: Marylise Borai
Extrayendo 456/1296: Lisette Beenders
Extrayendo 457/1296: Nina Caygill
Extrayendo 458/1296: Vanessa Pestana
Extrayendo 459/1296: Patricia Santana Carrascosa
Extrayendo 460/1296: Nuri Choi
Extrayendo 461/1296: Emily Azizi
Extrayendo 462/1296: Tanya Dunican
Extrayendo 463/1296: Rebecca Graf
Extrayendo 464/1296: Alexandra Chivescu
Extrayendo 465/1296: Alyssa Perrin De Ponte
Extrayendo 466/1296: Katarina Kiso
Extrayendo 467/1296: Helen Flynn
Extrayendo 468/1296: Nagy Henrietta
Extrayendo 469/1296: Júlia Mialaret
Extrayendo 470/1296: Anna Ubaldi
Extrayendo 471/1296: Rachel Mainfray
Extrayendo 472/1296: Lucie Guellec
Extrayendo 473/1296: Ruby Burns
Extrayendo 474/1296: Eliška Hodková
Extrayendo 475/1296: Anastasija Kilina
Extrayendo 476/1296: Africa Ndongo Tomas
Extrayendo 477/1296: Marleen Haimberger
Extrayendo 478/1296: Jule Schwarz
Extrayendo 479/1296: Elisabeth Miralles Carol
Extrayendo 480/1296: Andrea López Rubio
Extrayendo 481/1296: Justina Nenortaitė
Extrayendo 482/1296: Jennifer Falconer
Extrayendo 483/1296: Nikita Marsman
Extrayendo 484/1296: Stefania Elizabeth Ayala
Extrayendo 485/1296: Paula García
Extrayendo 486/1296: Julia Concha
Extrayendo 487/1296: Andrea Ruiz Estrada
Extrayendo 488/1296: Isabel Santiago Ruiz
Extrayendo 489/1296: Foix Vendrell Colet
Extrayendo 490/1296: Elena Laura Dossi
Extrayendo 491/1296: Emma Casula
Extrayendo 492/1296: Eleanor Heard
Extrayendo 493/1296: Sara Pérez
Extrayendo 494/1296: Susana De Oliveira Rocha
Extrayendo 495/1296: Marina Alventosa
Extrayendo 496/1296: Paula García Fernández
Extrayendo 497/1296: Lara Ibarra
Extrayendo 498/1296: Jana Phelan
Extrayendo 499/1296: Joana Dreux
Extrayendo 500/1296: Iris Reuterink
Extrayendo 501/1296: Ana Rita Dias
Extrayendo 502/1296: Anne Soizic Guion
Extrayendo 503/1296: Davianny Gonzalez
Extrayendo 504/1296: Julia Pankiewicz
Extrayendo 505/1296: Kateryna Ivasenko
Extrayendo 506/1296: Cristina Müntener
Extrayendo 507/1296: Barbara Wiesner
Extrayendo 508/1296: Suze Dercksen
Extrayendo 509/1296: Soili Herpe
Extrayendo 510/1296: Louise Huchedé
Extrayendo 511/1296: Anna Garcia Conill
Extrayendo 512/1296: Sandy Robson
Extrayendo 513/1296: Clodagh O’Connor
Extrayendo 514/1296: Andrea Peralta Mas
Extrayendo 515/1296: Daisy Burman
Extrayendo 516/1296: Suyen Arriaza
Extrayendo 517/1296: Aline Gägauf
Extrayendo 518/1296: Sandy Jager
Extrayendo 519/1296: Kinga Mazur
Extrayendo 520/1296: Mariela Koll Huesca
Extrayendo 521/1296: Emily Porter-Lynch
Extrayendo 522/1296: Yuliya Lennon
Extrayendo 523/1296: Anais Cavallin
Extrayendo 524/1296: Noelia Román Cruz
Extrayendo 525/1296: Susanne Foley
Extrayendo 526/1296: Samantha Sanders
Extrayendo 527/1296: Sarah Gaiao
Extrayendo 528/1296: Verena Buxkämper
Extrayendo 529/1296: Katia Ferrari
Extrayendo 530/1296: Maria Pardo Venegas
Extrayendo 531/1296: Tarryn Exall
Extrayendo 532/1296: Nile Bustinza
Extrayendo 533/1296: Sinéad Healy
Extrayendo 534/1296: Zeina El Zayadi
Extrayendo 535/1296: Nina Munetsi
Extrayendo 536/1296: Anaís Martínez Ortiz
Extrayendo 537/1296: Marion Botte
Extrayendo 538/1296: Nicole Bryer
Extrayendo 539/1296: Ana Hernandez Rubio
Extrayendo 540/1296: Raquel Sá
Extrayendo 541/1296: Yolanda Lozano
Extrayendo 542/1296: Melanie Almeida

## 6. Unión Men + Women

In [11]:
df_men["sexo"] = "men"
df_women["sexo"] = "women"

df_splits_men["sexo"] = "men"
df_splits_women["sexo"] = "women"

df_ranking_total = pd.concat(
    [df_men, df_women],
    ignore_index=True
)

df_splits_total = pd.concat(
    [df_splits_men, df_splits_women],
    ignore_index=True
)

df_ranking_total.to_csv(
    f"{RUTA_DATOS}/{evento}_hyrox_ranking_total.csv",
    index=False
)

df_splits_total.to_csv(
    f"{RUTA_DATOS}/{evento}_hyrox_splits_total.csv",
    index=False
)

print(df_ranking_total.shape)
print(df_splits_total.shape)

(3645, 9)
(109300, 11)